if(typeof Math.imul == "undefined" || (Math.imul(0xffffffff,5) == 0)) {
    Math.imul = function (a, b) {
        var ah  = (a >>> 16) & 0xffff;
        var al = a & 0xffff;
        var bh  = (b >>> 16) & 0xffff;
        var bl = b & 0xffff;
        // the shift by 0 fixes the sign on the high part
        // the final |0 converts the unsigned value into a signed value
        return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
    }
}


;(function(){
var f;
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var aa="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function ca(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function ea(a,b){null!=a&&this.append.apply(this,arguments)}f=ea.prototype;f.Ja="";f.set=function(a){this.Ja=""+a};f.append=function(a,b,c){this.Ja+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.Ja+=arguments[d];return this};f.clear=function(){this.Ja=""};f.toString=function(){return this.Ja};var ga;if("undefined"===typeof ha)var ha=function(){throw Error("No *print-fn* fn set for evaluation environment");};if("undefined"===typeof ja)var ja=function(){throw Error("No *print-err-fn* fn set for evaluation environment");};var ka=null;if("undefined"===typeof la)var la=null;function ma(){return new r(null,5,[na,!0,qa,!0,sa,!1,ta,!1,ua,null],null)}function v(a){return null!=a&&!1!==a}function wa(a){return a instanceof Array}function w(a,b){return a[n(null==b?null:b)]?!0:a._?!0:!1}
function y(a,b){var c=null==b?null:b.constructor,c=v(v(c)?c.qb:c)?c.$a:n(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function ya(a){var b=a.$a;return v(b)?b:""+z(a)}var Aa="undefined"!==typeof Symbol&&"function"===n(Symbol)?Symbol.iterator:"@@iterator";function Ba(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}function Ca(){}
var Da=function Da(b){if(null!=b&&null!=b.Y)return b.Y(b);var c=Da[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Da._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ICounted.-count",b);},Ea=function Ea(b,c){if(null!=b&&null!=b.O)return b.O(b,c);var d=Ea[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=Ea._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("ICollection.-conj",b);};function Fa(){}
var A=function A(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return A.a(arguments[0],arguments[1]);case 3:return A.g(arguments[0],arguments[1],arguments[2]);default:throw Error([z("Invalid arity: "),z(c.length)].join(""));}};
A.a=function(a,b){if(null!=a&&null!=a.P)return a.P(a,b);var c=A[n(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=A._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw y("IIndexed.-nth",a);};A.g=function(a,b,c){if(null!=a&&null!=a.ea)return a.ea(a,b,c);var d=A[n(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=A._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw y("IIndexed.-nth",a);};A.J=3;
var D=function D(b){if(null!=b&&null!=b.W)return b.W(b);var c=D[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=D._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ISeq.-first",b);},G=function G(b){if(null!=b&&null!=b.aa)return b.aa(b);var c=G[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=G._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ISeq.-rest",b);};function Ha(){}function Ia(){}
var Ja=function Ja(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return Ja.a(arguments[0],arguments[1]);case 3:return Ja.g(arguments[0],arguments[1],arguments[2]);default:throw Error([z("Invalid arity: "),z(c.length)].join(""));}};
Ja.a=function(a,b){if(null!=a&&null!=a.R)return a.R(a,b);var c=Ja[n(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=Ja._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw y("ILookup.-lookup",a);};Ja.g=function(a,b,c){if(null!=a&&null!=a.I)return a.I(a,b,c);var d=Ja[n(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=Ja._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw y("ILookup.-lookup",a);};Ja.J=3;
var Ka=function Ka(b,c,d){if(null!=b&&null!=b.Qa)return b.Qa(b,c,d);var e=Ka[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=Ka._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("IAssociative.-assoc",b);};function Ma(){}function Na(){}
var Oa=function Oa(b){if(null!=b&&null!=b.gb)return b.gb();var c=Oa[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Oa._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IMapEntry.-key",b);},Pa=function Pa(b){if(null!=b&&null!=b.hb)return b.hb();var c=Pa[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Pa._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IMapEntry.-val",b);};function Qa(){}
var Sa=function Sa(b,c,d){if(null!=b&&null!=b.ib)return b.ib(b,c,d);var e=Sa[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=Sa._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("IVector.-assoc-n",b);},Ta=function Ta(b){if(null!=b&&null!=b.ub)return b.state;var c=Ta[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Ta._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IDeref.-deref",b);};function Ua(){}
var Va=function Va(b){if(null!=b&&null!=b.L)return b.L(b);var c=Va[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Va._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IMeta.-meta",b);},Wa=function Wa(b,c){if(null!=b&&null!=b.N)return b.N(b,c);var d=Wa[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=Wa._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("IWithMeta.-with-meta",b);};function Ya(){}
var Za=function Za(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return Za.a(arguments[0],arguments[1]);case 3:return Za.g(arguments[0],arguments[1],arguments[2]);default:throw Error([z("Invalid arity: "),z(c.length)].join(""));}};
Za.a=function(a,b){if(null!=a&&null!=a.U)return a.U(a,b);var c=Za[n(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=Za._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw y("IReduce.-reduce",a);};Za.g=function(a,b,c){if(null!=a&&null!=a.V)return a.V(a,b,c);var d=Za[n(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=Za._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw y("IReduce.-reduce",a);};Za.J=3;
var $a=function $a(b,c){if(null!=b&&null!=b.m)return b.m(b,c);var d=$a[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=$a._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("IEquiv.-equiv",b);},ab=function ab(b){if(null!=b&&null!=b.H)return b.H(b);var c=ab[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=ab._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IHash.-hash",b);};function bb(){}
var cb=function cb(b){if(null!=b&&null!=b.T)return b.T(b);var c=cb[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=cb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ISeqable.-seq",b);};function db(){}function eb(){}
var H=function H(b,c){if(null!=b&&null!=b.pb)return b.pb(0,c);var d=H[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=H._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("IWriter.-write",b);},fb=function fb(b,c,d){if(null!=b&&null!=b.F)return b.F(b,c,d);var e=fb[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=fb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("IPrintWithWriter.-pr-writer",b);},hb=function hb(b,c,d){if(null!=b&&null!=
b.ob)return b.ob(0,c,d);var e=hb[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=hb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("IWatchable.-notify-watches",b);},ib=function ib(b){if(null!=b&&null!=b.Ra)return b.Ra(b);var c=ib[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=ib._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IEditableCollection.-as-transient",b);},jb=function jb(b,c){if(null!=b&&null!=b.Ya)return b.Ya(b,c);var d=jb[n(null==
b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=jb._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("ITransientCollection.-conj!",b);},kb=function kb(b){if(null!=b&&null!=b.Za)return b.Za(b);var c=kb[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=kb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ITransientCollection.-persistent!",b);},lb=function lb(b,c,d){if(null!=b&&null!=b.Sa)return b.Sa(b,c,d);var e=lb[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,
c,d):e.call(null,b,c,d);e=lb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("ITransientAssociative.-assoc!",b);},mb=function mb(b,c,d){if(null!=b&&null!=b.nb)return b.nb(0,c,d);var e=mb[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=mb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("ITransientVector.-assoc-n!",b);},nb=function nb(b){if(null!=b&&null!=b.kb)return b.kb();var c=nb[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=
nb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IChunk.-drop-first",b);},ob=function ob(b){if(null!=b&&null!=b.eb)return b.eb(b);var c=ob[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=ob._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IChunkedSeq.-chunked-first",b);},pb=function pb(b){if(null!=b&&null!=b.fb)return b.fb(b);var c=pb[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=pb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IChunkedSeq.-chunked-rest",
b);},sb=function sb(b){if(null!=b&&null!=b.cb)return b.cb(b);var c=sb[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=sb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IChunkedNext.-chunked-next",b);},tb=function tb(b,c){if(null!=b&&null!=b.Bb)return b.Bb(b,c);var d=tb[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=tb._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("IReset.-reset!",b);},ub=function ub(b){for(var c=[],d=arguments.length,e=0;;)if(e<
d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return ub.a(arguments[0],arguments[1]);case 3:return ub.g(arguments[0],arguments[1],arguments[2]);case 4:return ub.w(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return ub.D(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error([z("Invalid arity: "),z(c.length)].join(""));}};
ub.a=function(a,b){if(null!=a&&null!=a.Db)return a.Db(a,b);var c=ub[n(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=ub._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw y("ISwap.-swap!",a);};ub.g=function(a,b,c){if(null!=a&&null!=a.Eb)return a.Eb(a,b,c);var d=ub[n(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=ub._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw y("ISwap.-swap!",a);};
ub.w=function(a,b,c,d){if(null!=a&&null!=a.Fb)return a.Fb(a,b,c,d);var e=ub[n(null==a?null:a)];if(null!=e)return e.w?e.w(a,b,c,d):e.call(null,a,b,c,d);e=ub._;if(null!=e)return e.w?e.w(a,b,c,d):e.call(null,a,b,c,d);throw y("ISwap.-swap!",a);};ub.D=function(a,b,c,d,e){if(null!=a&&null!=a.Gb)return a.Gb(a,b,c,d,e);var g=ub[n(null==a?null:a)];if(null!=g)return g.D?g.D(a,b,c,d,e):g.call(null,a,b,c,d,e);g=ub._;if(null!=g)return g.D?g.D(a,b,c,d,e):g.call(null,a,b,c,d,e);throw y("ISwap.-swap!",a);};
ub.J=5;var vb=function vb(b){if(null!=b&&null!=b.Da)return b.Da(b);var c=vb[n(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=vb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IIterable.-iterator",b);};function wb(a){this.Kb=a;this.h=1073741824;this.A=0}wb.prototype.pb=function(a,b){return this.Kb.append(b)};function xb(a){var b=new ea;a.F(null,new wb(b),ma());return""+z(b)}
var yb="undefined"!==typeof Math.imul&&0!==Math.imul(4294967295,5)?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function zb(a){a=yb(a|0,-862048943);return yb(a<<15|a>>>-15,461845907)}function Ab(a,b){var c=(a|0)^(b|0);return yb(c<<13|c>>>-13,5)+-430675100|0}function Bb(a,b){var c=(a|0)^b,c=yb(c^c>>>16,-2048144789),c=yb(c^c>>>13,-1028477387);return c^c>>>16}
function Db(a){var b;a:{b=1;for(var c=0;;)if(b<a.length){var d=b+2,c=Ab(c,zb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16));b=d}else{b=c;break a}}b=1===(a.length&1)?b^zb(a.charCodeAt(a.length-1)):b;return Bb(b,yb(2,a.length))}var Eb={},Fb=0;function Gb(a){255<Fb&&(Eb={},Fb=0);var b=Eb[a];if("number"!==typeof b){a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)var e=c+1,d=yb(31,d)+a.charCodeAt(c),c=e;else{b=d;break a}else b=0;else b=0;Eb[a]=b;Fb+=1}return a=b}
function Hb(a){null!=a&&(a.h&4194304||a.Ob)?a=a.H(null):"number"===typeof a?a=Math.floor(a)%2147483647:!0===a?a=1:!1===a?a=0:"string"===typeof a?(a=Gb(a),0!==a&&(a=zb(a),a=Ab(0,a),a=Bb(a,4))):a=a instanceof Date?a.valueOf():null==a?0:ab(a);return a}function Ib(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function Jb(a,b,c,d,e){this.Va=a;this.name=b;this.Ia=c;this.Na=d;this.da=e;this.h=2154168321;this.A=4096}f=Jb.prototype;f.toString=function(){return this.Ia};f.equiv=function(a){return this.m(null,a)};
f.m=function(a,b){return b instanceof Jb?this.Ia===b.Ia:!1};f.call=function(){function a(a,b,c){return Kb?Kb(b,this,c):Lb.call(null,b,this,c)}function b(a,b){return I?I(b,this):Lb.call(null,b,this)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,0,e);case 3:return a.call(this,0,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.g=a;return c}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};
f.c=function(a){return I?I(a,this):Lb.call(null,a,this)};f.a=function(a,b){return Kb?Kb(a,this,b):Lb.call(null,a,this,b)};f.L=function(){return this.da};f.N=function(a,b){return new Jb(this.Va,this.name,this.Ia,this.Na,b)};f.H=function(){var a=this.Na;return null!=a?a:this.Na=a=Ib(Db(this.name),Gb(this.Va))};f.F=function(a,b){return H(b,this.Ia)};
function J(a){if(null==a)return null;if(null!=a&&(a.h&8388608||a.Cb))return a.T(null);if(wa(a)||"string"===typeof a)return 0===a.length?null:new K(a,0);if(w(bb,a))return cb(a);throw Error([z(a),z(" is not ISeqable")].join(""));}function M(a){if(null==a)return null;if(null!=a&&(a.h&64||a.Ea))return a.W(null);a=J(a);return null==a?null:D(a)}function Mb(a){return null!=a?null!=a&&(a.h&64||a.Ea)?a.aa(null):(a=J(a))?G(a):Nb:Nb}
function N(a){return null==a?null:null!=a&&(a.h&128||a.Xa)?a.Z(null):J(Mb(a))}var O=function O(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return O.c(arguments[0]);case 2:return O.a(arguments[0],arguments[1]);default:return O.u(arguments[0],arguments[1],new K(c.slice(2),0))}};O.c=function(){return!0};O.a=function(a,b){return null==a?null==b:a===b||$a(a,b)};
O.u=function(a,b,c){for(;;)if(O.a(a,b))if(N(c))a=b,b=M(c),c=N(c);else return O.a(b,M(c));else return!1};O.G=function(a){var b=M(a),c=N(a);a=M(c);c=N(c);return O.u(b,a,c)};O.J=2;function Ob(a){this.v=a}Ob.prototype.next=function(){if(null!=this.v){var a=M(this.v);this.v=N(this.v);return{value:a,done:!1}}return{value:null,done:!0}};function Pb(a){return new Ob(J(a))}function Rb(a,b){var c=zb(a),c=Ab(0,c);return Bb(c,b)}
function Sb(a){var b=0,c=1;for(a=J(a);;)if(null!=a)b+=1,c=yb(31,c)+Hb(M(a))|0,a=N(a);else return Rb(c,b)}var Tb=Rb(1,0);function Ub(a){var b=0,c=0;for(a=J(a);;)if(null!=a)b+=1,c=c+Hb(M(a))|0,a=N(a);else return Rb(c,b)}var Vb=Rb(0,0);Ca["null"]=!0;Da["null"]=function(){return 0};Date.prototype.m=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};$a.number=function(a,b){return a===b};Ua["function"]=!0;Va["function"]=function(){return null};ab._=function(a){return a[aa]||(a[aa]=++ba)};
function Wb(a){return a+1}function Xb(a){return Ta(a)}function Yb(a,b){var c=Da(a);if(0===c)return b.C?b.C():b.call(null);for(var d=A.a(a,0),e=1;;)if(e<c)var g=A.a(a,e),d=b.a?b.a(d,g):b.call(null,d,g),e=e+1;else return d}function Zb(a,b,c){var d=Da(a),e=c;for(c=0;;)if(c<d){var g=A.a(a,c),e=b.a?b.a(e,g):b.call(null,e,g);c+=1}else return e}
function $b(a,b){var c=a.length;if(0===a.length)return b.C?b.C():b.call(null);for(var d=a[0],e=1;;)if(e<c)var g=a[e],d=b.a?b.a(d,g):b.call(null,d,g),e=e+1;else return d}function ac(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c],e=b.a?b.a(e,g):b.call(null,e,g);c+=1}else return e}function bc(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.a?b.a(c,g):b.call(null,c,g);d+=1}else return c}function cc(a){return null!=a?a.h&2||a.tb?!0:a.h?!1:w(Ca,a):w(Ca,a)}
function dc(a){return null!=a?a.h&16||a.lb?!0:a.h?!1:w(Fa,a):w(Fa,a)}function ec(a,b){this.b=a;this.j=b}ec.prototype.ga=function(){return this.j<this.b.length};ec.prototype.next=function(){var a=this.b[this.j];this.j+=1;return a};function K(a,b){this.b=a;this.j=b;this.h=166199550;this.A=8192}f=K.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.P=function(a,b){var c=b+this.j;return c<this.b.length?this.b[c]:null};
f.ea=function(a,b,c){a=b+this.j;return a<this.b.length?this.b[a]:c};f.Da=function(){return new ec(this.b,this.j)};f.Z=function(){return this.j+1<this.b.length?new K(this.b,this.j+1):null};f.Y=function(){var a=this.b.length-this.j;return 0>a?0:a};f.H=function(){return Sb(this)};f.m=function(a,b){return fc.a?fc.a(this,b):fc.call(null,this,b)};f.U=function(a,b){return bc(this.b,b,this.b[this.j],this.j+1)};f.V=function(a,b,c){return bc(this.b,b,c,this.j)};f.W=function(){return this.b[this.j]};
f.aa=function(){return this.j+1<this.b.length?new K(this.b,this.j+1):Nb};f.T=function(){return this.j<this.b.length?this:null};f.O=function(a,b){return P.a?P.a(b,this):P.call(null,b,this)};K.prototype[Aa]=function(){return Pb(this)};function gc(a,b){return b<a.length?new K(a,b):null}
function hc(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return gc(arguments[0],0);case 2:return gc(arguments[0],arguments[1]);default:throw Error([z("Invalid arity: "),z(b.length)].join(""));}}$a._=function(a,b){return a===b};
var ic=function ic(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return ic.C();case 1:return ic.c(arguments[0]);case 2:return ic.a(arguments[0],arguments[1]);default:return ic.u(arguments[0],arguments[1],new K(c.slice(2),0))}};ic.C=function(){return jc};ic.c=function(a){return a};ic.a=function(a,b){return null!=a?Ea(a,b):Ea(Nb,b)};ic.u=function(a,b,c){for(;;)if(v(c))a=ic.a(a,b),b=M(c),c=N(c);else return ic.a(a,b)};
ic.G=function(a){var b=M(a),c=N(a);a=M(c);c=N(c);return ic.u(b,a,c)};ic.J=2;function lc(a){if(null!=a)if(null!=a&&(a.h&2||a.tb))a=a.Y(null);else if(wa(a))a=a.length;else if("string"===typeof a)a=a.length;else if(null!=a&&(a.h&8388608||a.Cb))a:{a=J(a);for(var b=0;;){if(cc(a)){a=b+Da(a);break a}a=N(a);b+=1}}else a=Da(a);else a=0;return a}function mc(a,b){for(var c=null;;){if(null==a)return c;if(0===b)return J(a)?M(a):c;if(dc(a))return A.g(a,b,c);if(J(a)){var d=N(a),e=b-1;a=d;b=e}else return c}}
function nc(){var a=oc,b=pc(lc(oc));if("number"!==typeof b)throw Error("index argument to nth must be a number");if(null==a)return a;if(null!=a&&(a.h&16||a.lb))return a.P(null,b);if(wa(a))return b<a.length?a[b]:null;if("string"===typeof a)return b<a.length?a.charAt(b):null;if(null!=a&&(a.h&64||a.Ea)){a:for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(J(a)){a=M(a);break a}throw Error("Index out of bounds");}if(dc(a)){a=A.a(a,b);break a}if(J(a))a=N(a),--b;else throw Error("Index out of bounds");
}return a}if(w(Fa,a))return A.a(a,b);throw Error([z("nth not supported on this type "),z(ya(null==a?null:a.constructor))].join(""));}
function Q(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return null;if(null!=a&&(a.h&16||a.lb))return a.ea(null,b,null);if(wa(a))return b<a.length?a[b]:null;if("string"===typeof a)return b<a.length?a.charAt(b):null;if(null!=a&&(a.h&64||a.Ea))return mc(a,b);if(w(Fa,a))return A.a(a,b);throw Error([z("nth not supported on this type "),z(ya(null==a?null:a.constructor))].join(""));}
function Lb(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return I(arguments[0],arguments[1]);case 3:return Kb(arguments[0],arguments[1],arguments[2]);default:throw Error([z("Invalid arity: "),z(b.length)].join(""));}}function I(a,b){return null==a?null:null!=a&&(a.h&256||a.mb)?a.R(null,b):wa(a)?b<a.length?a[b|0]:null:"string"===typeof a?b<a.length?a[b|0]:null:w(Ia,a)?Ja.a(a,b):null}
function Kb(a,b,c){return null!=a?null!=a&&(a.h&256||a.mb)?a.I(null,b,c):wa(a)?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:w(Ia,a)?Ja.g(a,b,c):c:c}var qc=function qc(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 3:return qc.g(arguments[0],arguments[1],arguments[2]);default:return qc.u(arguments[0],arguments[1],arguments[2],new K(c.slice(3),0))}};
qc.g=function(a,b,c){if(null!=a)a=Ka(a,b,c);else a:{a=[b];c=[c];b=a.length;var d=0,e;for(e=ib(rc);;)if(d<b){var g=d+1;e=e.Sa(null,a[d],c[d]);d=g}else{a=kb(e);break a}}return a};qc.u=function(a,b,c,d){for(;;)if(a=qc.g(a,b,c),v(d))b=M(d),c=M(N(d)),d=N(N(d));else return a};qc.G=function(a){var b=M(a),c=N(a);a=M(c);var d=N(c),c=M(d),d=N(d);return qc.u(b,a,c,d)};qc.J=3;function sc(a,b){this.f=a;this.o=b;this.h=393217;this.A=0}f=sc.prototype;f.L=function(){return this.o};
f.N=function(a,b){return new sc(this.f,b)};
f.call=function(){function a(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C,L,T,pa){a=this;return tc.Wa?tc.Wa(a.f,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C,L,T,pa):tc.call(null,a.f,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C,L,T,pa)}function b(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C,L,T){a=this;return a.f.ya?a.f.ya(b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C,L,T):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C,L,T)}function c(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C,L){a=this;return a.f.xa?a.f.xa(b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,
C,L):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C,L)}function d(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C){a=this;return a.f.wa?a.f.wa(b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,C)}function e(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F){a=this;return a.f.va?a.f.va(b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F)}function g(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E){a=this;return a.f.ua?a.f.ua(b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E):a.f.call(null,
b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E)}function h(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B){a=this;return a.f.ta?a.f.ta(b,c,d,e,g,h,k,l,m,p,q,t,u,x,B):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B)}function k(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x){a=this;return a.f.sa?a.f.sa(b,c,d,e,g,h,k,l,m,p,q,t,u,x):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,t,u,x)}function l(a,b,c,d,e,g,h,k,l,m,p,q,t,u){a=this;return a.f.ra?a.f.ra(b,c,d,e,g,h,k,l,m,p,q,t,u):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,t,u)}function m(a,b,c,d,e,g,h,k,l,m,p,q,t){a=this;
return a.f.qa?a.f.qa(b,c,d,e,g,h,k,l,m,p,q,t):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,t)}function p(a,b,c,d,e,g,h,k,l,m,p,q){a=this;return a.f.pa?a.f.pa(b,c,d,e,g,h,k,l,m,p,q):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q)}function q(a,b,c,d,e,g,h,k,l,m,p){a=this;return a.f.oa?a.f.oa(b,c,d,e,g,h,k,l,m,p):a.f.call(null,b,c,d,e,g,h,k,l,m,p)}function t(a,b,c,d,e,g,h,k,l,m){a=this;return a.f.Ba?a.f.Ba(b,c,d,e,g,h,k,l,m):a.f.call(null,b,c,d,e,g,h,k,l,m)}function u(a,b,c,d,e,g,h,k,l){a=this;return a.f.Aa?a.f.Aa(b,c,
d,e,g,h,k,l):a.f.call(null,b,c,d,e,g,h,k,l)}function x(a,b,c,d,e,g,h,k){a=this;return a.f.za?a.f.za(b,c,d,e,g,h,k):a.f.call(null,b,c,d,e,g,h,k)}function B(a,b,c,d,e,g,h){a=this;return a.f.fa?a.f.fa(b,c,d,e,g,h):a.f.call(null,b,c,d,e,g,h)}function E(a,b,c,d,e,g){a=this;return a.f.D?a.f.D(b,c,d,e,g):a.f.call(null,b,c,d,e,g)}function F(a,b,c,d,e){a=this;return a.f.w?a.f.w(b,c,d,e):a.f.call(null,b,c,d,e)}function L(a,b,c,d){a=this;return a.f.g?a.f.g(b,c,d):a.f.call(null,b,c,d)}function T(a,b,c){a=this;
return a.f.a?a.f.a(b,c):a.f.call(null,b,c)}function pa(a,b){a=this;return a.f.c?a.f.c(b):a.f.call(null,b)}function rb(a){a=this;return a.f.C?a.f.C():a.f.call(null)}var C=null,C=function(C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa,gb,qb,Cb,Qb,kc,Rc,rd,oe,bf){switch(arguments.length){case 1:return rb.call(this,C);case 2:return pa.call(this,C,da);case 3:return T.call(this,C,da,fa);case 4:return L.call(this,C,da,fa,ia);case 5:return F.call(this,C,da,fa,ia,oa);case 6:return E.call(this,C,da,fa,ia,oa,ra);case 7:return B.call(this,
C,da,fa,ia,oa,ra,va);case 8:return x.call(this,C,da,fa,ia,oa,ra,va,xa);case 9:return u.call(this,C,da,fa,ia,oa,ra,va,xa,za);case 10:return t.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga);case 11:return q.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La);case 12:return p.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra);case 13:return m.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa);case 14:return l.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa,gb);case 15:return k.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,
Xa,gb,qb);case 16:return h.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa,gb,qb,Cb);case 17:return g.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa,gb,qb,Cb,Qb);case 18:return e.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa,gb,qb,Cb,Qb,kc);case 19:return d.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa,gb,qb,Cb,Qb,kc,Rc);case 20:return c.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa,gb,qb,Cb,Qb,kc,Rc,rd);case 21:return b.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa,gb,qb,Cb,Qb,kc,Rc,rd,
oe);case 22:return a.call(this,C,da,fa,ia,oa,ra,va,xa,za,Ga,La,Ra,Xa,gb,qb,Cb,Qb,kc,Rc,rd,oe,bf)}throw Error("Invalid arity: "+arguments.length);};C.c=rb;C.a=pa;C.g=T;C.w=L;C.D=F;C.fa=E;C.za=B;C.Aa=x;C.Ba=u;C.oa=t;C.pa=q;C.qa=p;C.ra=m;C.sa=l;C.ta=k;C.ua=h;C.va=g;C.wa=e;C.xa=d;C.ya=c;C.vb=b;C.Wa=a;return C}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.C=function(){return this.f.C?this.f.C():this.f.call(null)};
f.c=function(a){return this.f.c?this.f.c(a):this.f.call(null,a)};f.a=function(a,b){return this.f.a?this.f.a(a,b):this.f.call(null,a,b)};f.g=function(a,b,c){return this.f.g?this.f.g(a,b,c):this.f.call(null,a,b,c)};f.w=function(a,b,c,d){return this.f.w?this.f.w(a,b,c,d):this.f.call(null,a,b,c,d)};f.D=function(a,b,c,d,e){return this.f.D?this.f.D(a,b,c,d,e):this.f.call(null,a,b,c,d,e)};f.fa=function(a,b,c,d,e,g){return this.f.fa?this.f.fa(a,b,c,d,e,g):this.f.call(null,a,b,c,d,e,g)};
f.za=function(a,b,c,d,e,g,h){return this.f.za?this.f.za(a,b,c,d,e,g,h):this.f.call(null,a,b,c,d,e,g,h)};f.Aa=function(a,b,c,d,e,g,h,k){return this.f.Aa?this.f.Aa(a,b,c,d,e,g,h,k):this.f.call(null,a,b,c,d,e,g,h,k)};f.Ba=function(a,b,c,d,e,g,h,k,l){return this.f.Ba?this.f.Ba(a,b,c,d,e,g,h,k,l):this.f.call(null,a,b,c,d,e,g,h,k,l)};f.oa=function(a,b,c,d,e,g,h,k,l,m){return this.f.oa?this.f.oa(a,b,c,d,e,g,h,k,l,m):this.f.call(null,a,b,c,d,e,g,h,k,l,m)};
f.pa=function(a,b,c,d,e,g,h,k,l,m,p){return this.f.pa?this.f.pa(a,b,c,d,e,g,h,k,l,m,p):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p)};f.qa=function(a,b,c,d,e,g,h,k,l,m,p,q){return this.f.qa?this.f.qa(a,b,c,d,e,g,h,k,l,m,p,q):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p,q)};f.ra=function(a,b,c,d,e,g,h,k,l,m,p,q,t){return this.f.ra?this.f.ra(a,b,c,d,e,g,h,k,l,m,p,q,t):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p,q,t)};
f.sa=function(a,b,c,d,e,g,h,k,l,m,p,q,t,u){return this.f.sa?this.f.sa(a,b,c,d,e,g,h,k,l,m,p,q,t,u):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p,q,t,u)};f.ta=function(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x){return this.f.ta?this.f.ta(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p,q,t,u,x)};f.ua=function(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B){return this.f.ua?this.f.ua(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B)};
f.va=function(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E){return this.f.va?this.f.va(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E)};f.wa=function(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F){return this.f.wa?this.f.wa(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F)};
f.xa=function(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L){return this.f.xa?this.f.xa(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L)};f.ya=function(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T){return this.f.ya?this.f.ya(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T):this.f.call(null,a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T)};
f.vb=function(a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T,pa){return tc.Wa?tc.Wa(this.f,a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T,pa):tc.call(null,this.f,a,b,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T,pa)};function uc(a,b){return"function"==n(a)?new sc(a,b):null==a?null:Wa(a,b)}function vc(a){var b=null!=a;return(b?null!=a?a.h&131072||a.yb||(a.h?0:w(Ua,a)):w(Ua,a):b)?Va(a):null}function wc(a){return null!=a?a.h&16777216||a.Qb?!0:a.h?!1:w(db,a):w(db,a)}
function xc(a){return null==a?!1:null!=a?a.h&1024||a.wb?!0:a.h?!1:w(Ma,a):w(Ma,a)}function yc(a){return null!=a?a.h&16384||a.Rb?!0:a.h?!1:w(Qa,a):w(Qa,a)}function zc(a){return null!=a?a.A&512||a.Mb?!0:!1:!1}function Ac(a){var b=[];ca(a,function(a,b){return function(a,c){return b.push(c)}}(a,b));return b}function Bc(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,--e,b+=1}var Cc={};function Dc(a){return null==a?!1:!1===a?!1:!0}
function Ec(a,b){var c=J(b);if(c){var d=M(c),c=N(c);return Fc?Fc(a,d,c):Gc.call(null,a,d,c)}return a.C?a.C():a.call(null)}function Hc(a,b,c){for(c=J(c);;)if(c){var d=M(c);b=a.a?a.a(b,d):a.call(null,b,d);c=N(c)}else return b}
function Gc(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return b=arguments[0],c=arguments[1],null!=c&&(c.h&524288||c.Ab)?c.U(null,b):wa(c)?$b(c,b):"string"===typeof c?$b(c,b):w(Ya,c)?Za.a(c,b):Ec(b,c);case 3:return Fc(arguments[0],arguments[1],arguments[2]);default:throw Error([z("Invalid arity: "),z(b.length)].join(""));}}
function Fc(a,b,c){return null!=c&&(c.h&524288||c.Ab)?c.V(null,a,b):wa(c)?ac(c,a,b):"string"===typeof c?ac(c,a,b):w(Ya,c)?Za.g(c,a,b):Hc(a,b,c)}function Ic(a){return a}var Jc=function Jc(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return Jc.C();case 1:return Jc.c(arguments[0]);case 2:return Jc.a(arguments[0],arguments[1]);default:return Jc.u(arguments[0],arguments[1],new K(c.slice(2),0))}};Jc.C=function(){return 0};Jc.c=function(a){return a};
Jc.a=function(a,b){return a+b};Jc.u=function(a,b,c){return Fc(Jc,a+b,c)};Jc.G=function(a){var b=M(a),c=N(a);a=M(c);c=N(c);return Jc.u(b,a,c)};Jc.J=2;function Kc(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)}function Lc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}function Mc(a){var b=1;for(a=J(a);;)if(a&&0<b)--b,a=N(a);else return a}
var z=function z(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return z.C();case 1:return z.c(arguments[0]);default:return z.u(arguments[0],new K(c.slice(1),0))}};z.C=function(){return""};z.c=function(a){return null==a?"":""+a};z.u=function(a,b){for(var c=new ea(""+z(a)),d=b;;)if(v(d))c=c.append(""+z(M(d))),d=N(d);else return c.toString()};z.G=function(a){var b=M(a);a=N(a);return z.u(b,a)};z.J=1;
function fc(a,b){var c;if(wc(b))if(cc(a)&&cc(b)&&lc(a)!==lc(b))c=!1;else a:{c=J(a);for(var d=J(b);;){if(null==c){c=null==d;break a}if(null!=d&&O.a(M(c),M(d)))c=N(c),d=N(d);else{c=!1;break a}}}else c=null;return Dc(c)}function Nc(a,b,c,d,e){this.o=a;this.first=b;this.Ca=c;this.count=d;this.l=e;this.h=65937646;this.A=8192}f=Nc.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.o};f.Z=function(){return 1===this.count?null:this.Ca};
f.Y=function(){return this.count};f.H=function(){var a=this.l;return null!=a?a:this.l=a=Sb(this)};f.m=function(a,b){return fc(this,b)};f.U=function(a,b){return Ec(b,this)};f.V=function(a,b,c){return Hc(b,c,this)};f.W=function(){return this.first};f.aa=function(){return 1===this.count?Nb:this.Ca};f.T=function(){return this};f.N=function(a,b){return new Nc(b,this.first,this.Ca,this.count,this.l)};f.O=function(a,b){return new Nc(this.o,b,this,this.count+1,null)};Nc.prototype[Aa]=function(){return Pb(this)};
function Oc(a){this.o=a;this.h=65937614;this.A=8192}f=Oc.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.o};f.Z=function(){return null};f.Y=function(){return 0};f.H=function(){return Tb};f.m=function(a,b){return(null!=b?b.h&33554432||b.Pb||(b.h?0:w(eb,b)):w(eb,b))||wc(b)?null==J(b):!1};f.U=function(a,b){return Ec(b,this)};f.V=function(a,b,c){return Hc(b,c,this)};f.W=function(){return null};f.aa=function(){return Nb};f.T=function(){return null};
f.N=function(a,b){return new Oc(b)};f.O=function(a,b){return new Nc(this.o,b,null,1,null)};var Nb=new Oc(null);Oc.prototype[Aa]=function(){return Pb(this)};function Pc(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;a:{c=0<b.length?new K(b.slice(0),0):null;if(c instanceof K&&0===c.j)b=c.b;else b:for(b=[];;)if(null!=c)b.push(c.W(null)),c=c.Z(null);else break b;for(var c=b.length,e=Nb;;)if(0<c)d=c-1,e=e.O(null,b[c-1]),c=d;else break a}return e}
function Qc(a,b,c,d){this.o=a;this.first=b;this.Ca=c;this.l=d;this.h=65929452;this.A=8192}f=Qc.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.o};f.Z=function(){return null==this.Ca?null:J(this.Ca)};f.H=function(){var a=this.l;return null!=a?a:this.l=a=Sb(this)};f.m=function(a,b){return fc(this,b)};f.U=function(a,b){return Ec(b,this)};f.V=function(a,b,c){return Hc(b,c,this)};f.W=function(){return this.first};
f.aa=function(){return null==this.Ca?Nb:this.Ca};f.T=function(){return this};f.N=function(a,b){return new Qc(b,this.first,this.Ca,this.l)};f.O=function(a,b){return new Qc(null,b,this,null)};Qc.prototype[Aa]=function(){return Pb(this)};function P(a,b){var c=null==b;return(c?c:null!=b&&(b.h&64||b.Ea))?new Qc(null,a,b,null):new Qc(null,a,J(b),null)}function R(a,b,c,d){this.Va=a;this.name=b;this.Ga=c;this.Na=d;this.h=2153775105;this.A=4096}f=R.prototype;f.toString=function(){return[z(":"),z(this.Ga)].join("")};
f.equiv=function(a){return this.m(null,a)};f.m=function(a,b){return b instanceof R?this.Ga===b.Ga:!1};f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return I(c,this);case 3:return Kb(c,this,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return I(c,this)};a.g=function(a,c,d){return Kb(c,this,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.c=function(a){return I(a,this)};
f.a=function(a,b){return Kb(a,this,b)};f.H=function(){var a=this.Na;return null!=a?a:this.Na=a=Ib(Db(this.name),Gb(this.Va))+2654435769|0};f.F=function(a,b){return H(b,[z(":"),z(this.Ga)].join(""))};var Sc=function Sc(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return Sc.c(arguments[0]);case 2:return Sc.a(arguments[0],arguments[1]);default:throw Error([z("Invalid arity: "),z(c.length)].join(""));}};
Sc.c=function(a){if(a instanceof R)return a;if(a instanceof Jb){var b;if(null!=a&&(a.A&4096||a.zb))b=a.Va;else throw Error([z("Doesn't support namespace: "),z(a)].join(""));return new R(b,Tc.c?Tc.c(a):Tc.call(null,a),a.Ia,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new R(b[0],b[1],a,null):new R(null,b[0],a,null)):null};Sc.a=function(a,b){return new R(a,b,[z(v(a)?[z(a),z("/")].join(""):null),z(b)].join(""),null)};Sc.J=2;
function Uc(a,b,c,d){this.o=a;this.Pa=b;this.v=c;this.l=d;this.h=32374988;this.A=1}f=Uc.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};function Vc(a){null!=a.Pa&&(a.v=a.Pa.C?a.Pa.C():a.Pa.call(null),a.Pa=null);return a.v}f.L=function(){return this.o};f.Z=function(){cb(this);return null==this.v?null:N(this.v)};f.H=function(){var a=this.l;return null!=a?a:this.l=a=Sb(this)};f.m=function(a,b){return fc(this,b)};f.U=function(a,b){return Ec(b,this)};
f.V=function(a,b,c){return Hc(b,c,this)};f.W=function(){cb(this);return null==this.v?null:M(this.v)};f.aa=function(){cb(this);return null!=this.v?Mb(this.v):Nb};f.T=function(){Vc(this);if(null==this.v)return null;for(var a=this.v;;)if(a instanceof Uc)a=Vc(a);else return this.v=a,J(this.v)};f.N=function(a,b){return new Uc(b,this.Pa,this.v,this.l)};f.O=function(a,b){return P(b,this)};Uc.prototype[Aa]=function(){return Pb(this)};function Wc(a,b){this.bb=a;this.end=b;this.h=2;this.A=0}
Wc.prototype.add=function(a){this.bb[this.end]=a;return this.end+=1};Wc.prototype.na=function(){var a=new Xc(this.bb,0,this.end);this.bb=null;return a};Wc.prototype.Y=function(){return this.end};function Xc(a,b,c){this.b=a;this.M=b;this.end=c;this.h=524306;this.A=0}f=Xc.prototype;f.Y=function(){return this.end-this.M};f.P=function(a,b){return this.b[this.M+b]};f.ea=function(a,b,c){return 0<=b&&b<this.end-this.M?this.b[this.M+b]:c};
f.kb=function(){if(this.M===this.end)throw Error("-drop-first of empty chunk");return new Xc(this.b,this.M+1,this.end)};f.U=function(a,b){return bc(this.b,b,this.b[this.M],this.M+1)};f.V=function(a,b,c){return bc(this.b,b,c,this.M)};function Yc(a,b,c,d){this.na=a;this.ka=b;this.o=c;this.l=d;this.h=31850732;this.A=1536}f=Yc.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.o};
f.Z=function(){if(1<Da(this.na))return new Yc(nb(this.na),this.ka,this.o,null);var a=cb(this.ka);return null==a?null:a};f.H=function(){var a=this.l;return null!=a?a:this.l=a=Sb(this)};f.m=function(a,b){return fc(this,b)};f.W=function(){return A.a(this.na,0)};f.aa=function(){return 1<Da(this.na)?new Yc(nb(this.na),this.ka,this.o,null):null==this.ka?Nb:this.ka};f.T=function(){return this};f.eb=function(){return this.na};f.fb=function(){return null==this.ka?Nb:this.ka};
f.N=function(a,b){return new Yc(this.na,this.ka,b,this.l)};f.O=function(a,b){return P(b,this)};f.cb=function(){return null==this.ka?null:this.ka};Yc.prototype[Aa]=function(){return Pb(this)};function Zc(a,b){return 0===Da(a)?b:new Yc(a,b,null,null)}function $c(a,b){a.add(b)}function ad(a){for(var b=[];;)if(J(a))b.push(M(a)),a=N(a);else return b}function bd(a,b){if(cc(a))return lc(a);for(var c=a,d=b,e=0;;)if(0<d&&J(c))c=N(c),--d,e+=1;else return e}
var cd=function cd(b){return null==b?null:null==N(b)?J(M(b)):P(M(b),cd(N(b)))},dd=function dd(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return dd.C();case 1:return dd.c(arguments[0]);case 2:return dd.a(arguments[0],arguments[1]);default:return dd.u(arguments[0],arguments[1],new K(c.slice(2),0))}};dd.C=function(){return ib(jc)};dd.c=function(a){return a};dd.a=function(a,b){return jb(a,b)};
dd.u=function(a,b,c){for(;;)if(a=jb(a,b),v(c))b=M(c),c=N(c);else return a};dd.G=function(a){var b=M(a),c=N(a);a=M(c);c=N(c);return dd.u(b,a,c)};dd.J=2;
function ed(a,b,c){var d=J(c);if(0===b)return a.C?a.C():a.call(null);c=D(d);var e=G(d);if(1===b)return a.c?a.c(c):a.c?a.c(c):a.call(null,c);var d=D(e),g=G(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=D(g),h=G(g);if(3===b)return a.g?a.g(c,d,e):a.g?a.g(c,d,e):a.call(null,c,d,e);var g=D(h),k=G(h);if(4===b)return a.w?a.w(c,d,e,g):a.w?a.w(c,d,e,g):a.call(null,c,d,e,g);var h=D(k),l=G(k);if(5===b)return a.D?a.D(c,d,e,g,h):a.D?a.D(c,d,e,g,h):a.call(null,c,d,e,g,h);var k=D(l),m=G(l);
if(6===b)return a.fa?a.fa(c,d,e,g,h,k):a.fa?a.fa(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);var l=D(m),p=G(m);if(7===b)return a.za?a.za(c,d,e,g,h,k,l):a.za?a.za(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);var m=D(p),q=G(p);if(8===b)return a.Aa?a.Aa(c,d,e,g,h,k,l,m):a.Aa?a.Aa(c,d,e,g,h,k,l,m):a.call(null,c,d,e,g,h,k,l,m);var p=D(q),t=G(q);if(9===b)return a.Ba?a.Ba(c,d,e,g,h,k,l,m,p):a.Ba?a.Ba(c,d,e,g,h,k,l,m,p):a.call(null,c,d,e,g,h,k,l,m,p);var q=D(t),u=G(t);if(10===b)return a.oa?a.oa(c,d,e,g,h,k,l,m,p,
q):a.oa?a.oa(c,d,e,g,h,k,l,m,p,q):a.call(null,c,d,e,g,h,k,l,m,p,q);var t=D(u),x=G(u);if(11===b)return a.pa?a.pa(c,d,e,g,h,k,l,m,p,q,t):a.pa?a.pa(c,d,e,g,h,k,l,m,p,q,t):a.call(null,c,d,e,g,h,k,l,m,p,q,t);var u=D(x),B=G(x);if(12===b)return a.qa?a.qa(c,d,e,g,h,k,l,m,p,q,t,u):a.qa?a.qa(c,d,e,g,h,k,l,m,p,q,t,u):a.call(null,c,d,e,g,h,k,l,m,p,q,t,u);var x=D(B),E=G(B);if(13===b)return a.ra?a.ra(c,d,e,g,h,k,l,m,p,q,t,u,x):a.ra?a.ra(c,d,e,g,h,k,l,m,p,q,t,u,x):a.call(null,c,d,e,g,h,k,l,m,p,q,t,u,x);var B=D(E),
F=G(E);if(14===b)return a.sa?a.sa(c,d,e,g,h,k,l,m,p,q,t,u,x,B):a.sa?a.sa(c,d,e,g,h,k,l,m,p,q,t,u,x,B):a.call(null,c,d,e,g,h,k,l,m,p,q,t,u,x,B);var E=D(F),L=G(F);if(15===b)return a.ta?a.ta(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E):a.ta?a.ta(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E):a.call(null,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E);var F=D(L),T=G(L);if(16===b)return a.ua?a.ua(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F):a.ua?a.ua(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F):a.call(null,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F);var L=D(T),pa=G(T);if(17===b)return a.va?
a.va(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L):a.va?a.va(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L):a.call(null,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L);var T=D(pa),rb=G(pa);if(18===b)return a.wa?a.wa(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T):a.wa?a.wa(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T):a.call(null,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T);pa=D(rb);rb=G(rb);if(19===b)return a.xa?a.xa(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T,pa):a.xa?a.xa(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T,pa):a.call(null,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T,pa);var C=
D(rb);G(rb);if(20===b)return a.ya?a.ya(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T,pa,C):a.ya?a.ya(c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T,pa,C):a.call(null,c,d,e,g,h,k,l,m,p,q,t,u,x,B,E,F,L,T,pa,C);throw Error("Only up to 20 arguments supported on functions");}
function tc(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return fd(arguments[0],arguments[1]);case 3:return gd(arguments[0],arguments[1],arguments[2]);case 4:b=arguments[0];c=P(arguments[1],P(arguments[2],arguments[3]));d=b.J;if(b.G)var e=bd(c,d+1),b=e<=d?ed(b,e,c):b.G(c);else b=b.apply(b,ad(c));return b;case 5:return hd(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:return id(arguments[0],arguments[1],arguments[2],
arguments[3],arguments[4],new K(b.slice(5),0))}}function fd(a,b){var c=a.J;if(a.G){var d=bd(b,c+1);return d<=c?ed(a,d,b):a.G(b)}return a.apply(a,ad(b))}function gd(a,b,c){b=P(b,c);c=a.J;if(a.G){var d=bd(b,c+1);return d<=c?ed(a,d,b):a.G(b)}return a.apply(a,ad(b))}function hd(a,b,c,d,e){b=P(b,P(c,P(d,e)));c=a.J;return a.G?(d=bd(b,c+1),d<=c?ed(a,d,b):a.G(b)):a.apply(a,ad(b))}function id(a,b,c,d,e,g){b=P(b,P(c,P(d,P(e,cd(g)))));c=a.J;return a.G?(d=bd(b,c+1),d<=c?ed(a,d,b):a.G(b)):a.apply(a,ad(b))}
var jd=function jd(){"undefined"===typeof ga&&(ga=function(b,c){this.Jb=b;this.Ib=c;this.h=393216;this.A=0},ga.prototype.N=function(b,c){return new ga(this.Jb,c)},ga.prototype.L=function(){return this.Ib},ga.prototype.ga=function(){return!1},ga.prototype.next=function(){return Error("No such element")},ga.prototype.remove=function(){return Error("Unsupported operation")},ga.Sb=function(){return new S(null,2,5,kd,[uc(ld,new r(null,1,[md,Pc(nd,Pc(jc))],null)),od],null)},ga.qb=!0,ga.$a="cljs.core/t_cljs$core9866",
ga.Hb=function(b){return H(b,"cljs.core/t_cljs$core9866")});return new ga(jd,pd)};function qd(a,b){for(;;){if(null==J(b))return!0;var c;c=M(b);c=a.c?a.c(c):a.call(null,c);if(v(c)){c=a;var d=N(b);a=c;b=d}else return!1}}function sd(a,b,c,d){this.state=a;this.o=b;this.Lb=c;this.sb=d;this.A=16386;this.h=6455296}f=sd.prototype;f.equiv=function(a){return this.m(null,a)};f.m=function(a,b){return this===b};f.ub=function(){return this.state};f.L=function(){return this.o};
f.ob=function(a,b,c){a=J(this.sb);for(var d=null,e=0,g=0;;)if(g<e){var h=d.P(null,g),k=Q(h,0),h=Q(h,1);h.w?h.w(k,this,b,c):h.call(null,k,this,b,c);g+=1}else if(a=J(a))zc(a)?(d=ob(a),a=pb(a),k=d,e=lc(d),d=k):(d=M(a),k=Q(d,0),h=Q(d,1),h.w?h.w(k,this,b,c):h.call(null,k,this,b,c),a=N(a),d=null,e=0),g=0;else return null};f.H=function(){return this[aa]||(this[aa]=++ba)};
function td(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return ud(arguments[0]);default:return c=arguments[0],b=new K(b.slice(1),0),d=null!=b&&(b.h&64||b.Ea)?fd(vd,b):b,b=I(d,sa),d=I(d,wd),new sd(c,b,d,null)}}function ud(a){return new sd(a,null,null,null)}
function xd(a,b){if(a instanceof sd){var c=a.Lb;if(null!=c&&!v(c.c?c.c(b):c.call(null,b)))throw Error([z("Assert failed: "),z("Validator rejected reference state"),z("\n"),z(function(){var a=Pc(yd,zd);return Ad.c?Ad.c(a):Ad.call(null,a)}())].join(""));c=a.state;a.state=b;null!=a.sb&&hb(a,c,b);return b}return tb(a,b)}
var Bd=function Bd(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return Bd.a(arguments[0],arguments[1]);case 3:return Bd.g(arguments[0],arguments[1],arguments[2]);case 4:return Bd.w(arguments[0],arguments[1],arguments[2],arguments[3]);default:return Bd.u(arguments[0],arguments[1],arguments[2],arguments[3],new K(c.slice(4),0))}};Bd.a=function(a,b){var c;a instanceof sd?(c=a.state,c=b.c?b.c(c):b.call(null,c),c=xd(a,c)):c=ub.a(a,b);return c};
Bd.g=function(a,b,c){if(a instanceof sd){var d=a.state;b=b.a?b.a(d,c):b.call(null,d,c);a=xd(a,b)}else a=ub.g(a,b,c);return a};Bd.w=function(a,b,c,d){if(a instanceof sd){var e=a.state;b=b.g?b.g(e,c,d):b.call(null,e,c,d);a=xd(a,b)}else a=ub.w(a,b,c,d);return a};Bd.u=function(a,b,c,d,e){return a instanceof sd?xd(a,hd(b,a.state,c,d,e)):ub.D(a,b,c,d,e)};Bd.G=function(a){var b=M(a),c=N(a);a=M(c);var d=N(c),c=M(d),e=N(d),d=M(e),e=N(e);return Bd.u(b,a,c,d,e)};Bd.J=4;
var U=function U(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return U.c(arguments[0]);case 2:return U.a(arguments[0],arguments[1]);case 3:return U.g(arguments[0],arguments[1],arguments[2]);case 4:return U.w(arguments[0],arguments[1],arguments[2],arguments[3]);default:return U.u(arguments[0],arguments[1],arguments[2],arguments[3],new K(c.slice(4),0))}};
U.c=function(a){return function(b){return function(){function c(c,d){var e=a.c?a.c(d):a.call(null,d);return b.a?b.a(c,e):b.call(null,c,e)}function d(a){return b.c?b.c(a):b.call(null,a)}function e(){return b.C?b.C():b.call(null)}var g=null,h=function(){function c(a,b,e){var g=null;if(2<arguments.length){for(var g=0,h=Array(arguments.length-2);g<h.length;)h[g]=arguments[g+2],++g;g=new K(h,0)}return d.call(this,a,b,g)}function d(c,e,g){e=gd(a,e,g);return b.a?b.a(c,e):b.call(null,c,e)}c.J=2;c.G=function(a){var b=
M(a);a=N(a);var c=M(a);a=Mb(a);return d(b,c,a)};c.u=d;return c}(),g=function(a,b,g){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,a);case 2:return c.call(this,a,b);default:var p=null;if(2<arguments.length){for(var p=0,q=Array(arguments.length-2);p<q.length;)q[p]=arguments[p+2],++p;p=new K(q,0)}return h.u(a,b,p)}throw Error("Invalid arity: "+arguments.length);};g.J=2;g.G=h.G;g.C=e;g.c=d;g.a=c;g.u=h.u;return g}()}};
U.a=function(a,b){return new Uc(null,function(){var c=J(b);if(c){if(zc(c)){for(var d=ob(c),e=lc(d),g=new Wc(Array(e),0),h=0;;)if(h<e)$c(g,function(){var b=A.a(d,h);return a.c?a.c(b):a.call(null,b)}()),h+=1;else break;return Zc(g.na(),U.a(a,pb(c)))}return P(function(){var b=M(c);return a.c?a.c(b):a.call(null,b)}(),U.a(a,Mb(c)))}return null},null,null)};
U.g=function(a,b,c){return new Uc(null,function(){var d=J(b),e=J(c);if(d&&e){var g=P,h;h=M(d);var k=M(e);h=a.a?a.a(h,k):a.call(null,h,k);d=g(h,U.g(a,Mb(d),Mb(e)))}else d=null;return d},null,null)};U.w=function(a,b,c,d){return new Uc(null,function(){var e=J(b),g=J(c),h=J(d);if(e&&g&&h){var k=P,l;l=M(e);var m=M(g),p=M(h);l=a.g?a.g(l,m,p):a.call(null,l,m,p);e=k(l,U.w(a,Mb(e),Mb(g),Mb(h)))}else e=null;return e},null,null)};
U.u=function(a,b,c,d,e){var g=function k(a){return new Uc(null,function(){var b=U.a(J,a);return qd(Ic,b)?P(U.a(M,b),k(U.a(Mb,b))):null},null,null)};return U.a(function(){return function(b){return fd(a,b)}}(g),g(ic.u(e,d,hc([c,b],0))))};U.G=function(a){var b=M(a),c=N(a);a=M(c);var d=N(c),c=M(d),e=N(d),d=M(e),e=N(e);return U.u(b,a,c,d,e)};U.J=4;
function Cd(a,b){if("number"!==typeof a)throw Error([z("Assert failed: "),z(function(){var a=Pc(Dd,Ed);return Ad.c?Ad.c(a):Ad.call(null,a)}())].join(""));return new Uc(null,function(){if(0<a){var c=J(b);return c?P(M(c),Cd(a-1,Mb(c))):null}return null},null,null)}function Fd(a){return new Uc(null,function(){return P(a,Fd(a))},null,null)}
function Gd(a,b){var c;a:{c=Cc;for(var d=a,e=J(b);;)if(e)if(null!=d?d.h&256||d.mb||(d.h?0:w(Ia,d)):w(Ia,d)){d=Kb(d,M(e),c);if(c===d){c=null;break a}e=N(e)}else{c=null;break a}else{c=d;break a}}return c}
var Hd=function Hd(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 3:return Hd.g(arguments[0],arguments[1],arguments[2]);case 4:return Hd.w(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return Hd.D(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return Hd.fa(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:return Hd.u(arguments[0],arguments[1],arguments[2],arguments[3],
arguments[4],arguments[5],new K(c.slice(6),0))}};Hd.g=function(a,b,c){var d=Q(b,0);b=Mc(b);return v(b)?qc.g(a,d,Hd.g(I(a,d),b,c)):qc.g(a,d,function(){var b=I(a,d);return c.c?c.c(b):c.call(null,b)}())};Hd.w=function(a,b,c,d){var e=Q(b,0);b=Mc(b);return v(b)?qc.g(a,e,Hd.w(I(a,e),b,c,d)):qc.g(a,e,function(){var b=I(a,e);return c.a?c.a(b,d):c.call(null,b,d)}())};
Hd.D=function(a,b,c,d,e){var g=Q(b,0);b=Mc(b);return v(b)?qc.g(a,g,Hd.D(I(a,g),b,c,d,e)):qc.g(a,g,function(){var b=I(a,g);return c.g?c.g(b,d,e):c.call(null,b,d,e)}())};Hd.fa=function(a,b,c,d,e,g){var h=Q(b,0);b=Mc(b);return v(b)?qc.g(a,h,Hd.fa(I(a,h),b,c,d,e,g)):qc.g(a,h,function(){var b=I(a,h);return c.w?c.w(b,d,e,g):c.call(null,b,d,e,g)}())};Hd.u=function(a,b,c,d,e,g,h){var k=Q(b,0);b=Mc(b);return v(b)?qc.g(a,k,id(Hd,I(a,k),b,c,d,hc([e,g,h],0))):qc.g(a,k,id(c,I(a,k),d,e,g,hc([h],0)))};
Hd.G=function(a){var b=M(a),c=N(a);a=M(c);var d=N(c),c=M(d),e=N(d),d=M(e),g=N(e),e=M(g),h=N(g),g=M(h),h=N(h);return Hd.u(b,a,c,d,e,g,h)};Hd.J=6;function Id(a,b){this.B=a;this.b=b}function Jd(a){return new Id(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function Kd(a){a=a.i;return 32>a?0:a-1>>>5<<5}function Ld(a,b,c){for(;;){if(0===b)return c;var d=Jd(a);d.b[0]=c;c=d;b-=5}}
var Md=function Md(b,c,d,e){var g=new Id(d.B,Ba(d.b)),h=b.i-1>>>c&31;5===c?g.b[h]=e:(d=d.b[h],b=null!=d?Md(b,c-5,d,e):Ld(null,c-5,e),g.b[h]=b);return g};function Nd(a,b){throw Error([z("No item "),z(a),z(" in vector of length "),z(b)].join(""));}function Od(a,b){if(b>=Kd(a))return a.X;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.b[b>>>d&31],d=e;else return c.b}function Pd(a,b){return 0<=b&&b<a.i?Od(a,b):Nd(b,a.i)}
var Qd=function Qd(b,c,d,e,g){var h=new Id(d.B,Ba(d.b));if(0===c)h.b[e&31]=g;else{var k=e>>>c&31;b=Qd(b,c-5,d.b[k],e,g);h.b[k]=b}return h};function Rd(a,b,c,d,e,g){this.j=a;this.ab=b;this.b=c;this.la=d;this.start=e;this.end=g}Rd.prototype.ga=function(){return this.j<this.end};Rd.prototype.next=function(){32===this.j-this.ab&&(this.b=Od(this.la,this.j),this.ab+=32);var a=this.b[this.j&31];this.j+=1;return a};
function S(a,b,c,d,e,g){this.o=a;this.i=b;this.shift=c;this.root=d;this.X=e;this.l=g;this.h=167668511;this.A=8196}f=S.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.R=function(a,b){return Ja.g(this,b,null)};f.I=function(a,b,c){return"number"===typeof b?A.g(this,b,c):c};f.P=function(a,b){return Pd(this,b)[b&31]};f.ea=function(a,b,c){return 0<=b&&b<this.i?Od(this,b)[b&31]:c};
f.ib=function(a,b,c){if(0<=b&&b<this.i)return Kd(this)<=b?(a=Ba(this.X),a[b&31]=c,new S(this.o,this.i,this.shift,this.root,a,null)):new S(this.o,this.i,this.shift,Qd(this,this.shift,this.root,b,c),this.X,null);if(b===this.i)return Ea(this,c);throw Error([z("Index "),z(b),z(" out of bounds  [0,"),z(this.i),z("]")].join(""));};f.Da=function(){var a=this.i;return new Rd(0,0,0<lc(this)?Od(this,0):null,this,0,a)};f.L=function(){return this.o};f.Y=function(){return this.i};
f.gb=function(){return A.a(this,0)};f.hb=function(){return A.a(this,1)};f.H=function(){var a=this.l;return null!=a?a:this.l=a=Sb(this)};f.m=function(a,b){if(b instanceof S)if(this.i===lc(b))for(var c=vb(this),d=vb(b);;)if(v(c.ga())){var e=c.next(),g=d.next();if(!O.a(e,g))return!1}else return!0;else return!1;else return fc(this,b)};f.Ra=function(){return new Sd(this.i,this.shift,Td.c?Td.c(this.root):Td.call(null,this.root),Ud.c?Ud.c(this.X):Ud.call(null,this.X))};f.U=function(a,b){return Yb(this,b)};
f.V=function(a,b,c){a=0;for(var d=c;;)if(a<this.i){var e=Od(this,a);c=e.length;a:for(var g=0;;)if(g<c)var h=e[g],d=b.a?b.a(d,h):b.call(null,d,h),g=g+1;else{e=d;break a}a+=c;d=e}else return d};f.Qa=function(a,b,c){if("number"===typeof b)return Sa(this,b,c);throw Error("Vector's key for assoc must be a number.");};
f.T=function(){if(0===this.i)return null;if(32>=this.i)return new K(this.X,0);var a;a:{a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.b[0];else{a=a.b;break a}}return Vd?Vd(this,a,0,0):Wd.call(null,this,a,0,0)};f.N=function(a,b){return new S(b,this.i,this.shift,this.root,this.X,this.l)};
f.O=function(a,b){if(32>this.i-Kd(this)){for(var c=this.X.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.X[e],e+=1;else break;d[c]=b;return new S(this.o,this.i+1,this.shift,this.root,d,null)}c=(d=this.i>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=Jd(null),d.b[0]=this.root,e=Ld(null,this.shift,new Id(null,this.X)),d.b[1]=e):d=Md(this,this.shift,this.root,new Id(null,this.X));return new S(this.o,this.i+1,c,d,[b],null)};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.P(null,c);case 3:return this.ea(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.P(null,c)};a.g=function(a,c,d){return this.ea(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.c=function(a){return this.P(null,a)};f.a=function(a,b){return this.ea(null,a,b)};
var kd=new Id(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),jc=new S(null,0,5,kd,[],Tb);S.prototype[Aa]=function(){return Pb(this)};function Xd(a){if(wa(a))a:{var b=a.length;if(32>b)a=new S(null,b,5,kd,a,null);else for(var c=32,d=(new S(null,32,5,kd,a.slice(0,32),null)).Ra(null);;)if(c<b)var e=c+1,d=dd.a(d,a[c]),c=e;else{a=kb(d);break a}}else a=kb(Fc(jb,ib(jc),a));return a}
function Yd(a,b,c,d,e,g){this.ca=a;this.node=b;this.j=c;this.M=d;this.o=e;this.l=g;this.h=32375020;this.A=1536}f=Yd.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.o};f.Z=function(){if(this.M+1<this.node.length){var a;a=this.ca;var b=this.node,c=this.j,d=this.M+1;a=Vd?Vd(a,b,c,d):Wd.call(null,a,b,c,d);return null==a?null:a}return sb(this)};f.H=function(){var a=this.l;return null!=a?a:this.l=a=Sb(this)};
f.m=function(a,b){return fc(this,b)};f.U=function(a,b){var c;c=this.ca;var d=this.j+this.M,e=lc(this.ca);c=Zd?Zd(c,d,e):$d.call(null,c,d,e);return Yb(c,b)};f.V=function(a,b,c){a=this.ca;var d=this.j+this.M,e=lc(this.ca);a=Zd?Zd(a,d,e):$d.call(null,a,d,e);return Zb(a,b,c)};f.W=function(){return this.node[this.M]};f.aa=function(){if(this.M+1<this.node.length){var a;a=this.ca;var b=this.node,c=this.j,d=this.M+1;a=Vd?Vd(a,b,c,d):Wd.call(null,a,b,c,d);return null==a?Nb:a}return pb(this)};f.T=function(){return this};
f.eb=function(){var a=this.node;return new Xc(a,this.M,a.length)};f.fb=function(){var a=this.j+this.node.length;if(a<Da(this.ca)){var b=this.ca,c=Od(this.ca,a);return Vd?Vd(b,c,a,0):Wd.call(null,b,c,a,0)}return Nb};f.N=function(a,b){return ae?ae(this.ca,this.node,this.j,this.M,b):Wd.call(null,this.ca,this.node,this.j,this.M,b)};f.O=function(a,b){return P(b,this)};
f.cb=function(){var a=this.j+this.node.length;if(a<Da(this.ca)){var b=this.ca,c=Od(this.ca,a);return Vd?Vd(b,c,a,0):Wd.call(null,b,c,a,0)}return null};Yd.prototype[Aa]=function(){return Pb(this)};
function Wd(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 3:return b=arguments[0],c=arguments[1],d=arguments[2],new Yd(b,Pd(b,c),c,d,null,null);case 4:return Vd(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return ae(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error([z("Invalid arity: "),z(b.length)].join(""));}}function Vd(a,b,c,d){return new Yd(a,b,c,d,null,null)}
function ae(a,b,c,d,e){return new Yd(a,b,c,d,e,null)}function be(a,b,c,d,e){this.o=a;this.la=b;this.start=c;this.end=d;this.l=e;this.h=167666463;this.A=8192}f=be.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.R=function(a,b){return Ja.g(this,b,null)};f.I=function(a,b,c){return"number"===typeof b?A.g(this,b,c):c};f.P=function(a,b){return 0>b||this.end<=this.start+b?Nd(b,this.end-this.start):A.a(this.la,this.start+b)};
f.ea=function(a,b,c){return 0>b||this.end<=this.start+b?c:A.g(this.la,this.start+b,c)};f.ib=function(a,b,c){var d=this.start+b;a=this.o;c=qc.g(this.la,d,c);b=this.start;var e=this.end,d=d+1,d=e>d?e:d;return ce.D?ce.D(a,c,b,d,null):ce.call(null,a,c,b,d,null)};f.L=function(){return this.o};f.Y=function(){return this.end-this.start};f.H=function(){var a=this.l;return null!=a?a:this.l=a=Sb(this)};f.m=function(a,b){return fc(this,b)};f.U=function(a,b){return Yb(this,b)};
f.V=function(a,b,c){return Zb(this,b,c)};f.Qa=function(a,b,c){if("number"===typeof b)return Sa(this,b,c);throw Error("Subvec's key for assoc must be a number.");};f.T=function(){var a=this;return function(b){return function d(e){return e===a.end?null:P(A.a(a.la,e),new Uc(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};f.N=function(a,b){return ce.D?ce.D(b,this.la,this.start,this.end,this.l):ce.call(null,b,this.la,this.start,this.end,this.l)};
f.O=function(a,b){var c=this.o,d=Sa(this.la,this.end,b),e=this.start,g=this.end+1;return ce.D?ce.D(c,d,e,g,null):ce.call(null,c,d,e,g,null)};f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.P(null,c);case 3:return this.ea(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.P(null,c)};a.g=function(a,c,d){return this.ea(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};
f.c=function(a){return this.P(null,a)};f.a=function(a,b){return this.ea(null,a,b)};be.prototype[Aa]=function(){return Pb(this)};function ce(a,b,c,d,e){for(;;)if(b instanceof be)c=b.start+c,d=b.start+d,b=b.la;else{var g=lc(b);if(0>c||0>d||c>g||d>g)throw Error("Index out of bounds");return new be(a,b,c,d,e)}}
function $d(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return b=arguments[0],Zd(b,arguments[1],lc(b));case 3:return Zd(arguments[0],arguments[1],arguments[2]);default:throw Error([z("Invalid arity: "),z(b.length)].join(""));}}function Zd(a,b,c){return ce(null,a,b,c,null)}function de(a,b){return a===b.B?b:new Id(a,Ba(b.b))}function Td(a){return new Id({},Ba(a.b))}
function Ud(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Bc(a,0,b,0,a.length);return b}var ee=function ee(b,c,d,e){d=de(b.root.B,d);var g=b.i-1>>>c&31;if(5===c)b=e;else{var h=d.b[g];b=null!=h?ee(b,c-5,h,e):Ld(b.root.B,c-5,e)}d.b[g]=b;return d};function Sd(a,b,c,d){this.i=a;this.shift=b;this.root=c;this.X=d;this.A=88;this.h=275}f=Sd.prototype;
f.Ya=function(a,b){if(this.root.B){if(32>this.i-Kd(this))this.X[this.i&31]=b;else{var c=new Id(this.root.B,this.X),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.X=d;if(this.i>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=Ld(this.root.B,this.shift,c);this.root=new Id(this.root.B,d);this.shift=e}else this.root=ee(this,this.shift,this.root,c)}this.i+=1;return this}throw Error("conj! after persistent!");};f.Za=function(){if(this.root.B){this.root.B=null;var a=this.i-Kd(this),b=Array(a);Bc(this.X,0,b,0,a);return new S(null,this.i,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Sa=function(a,b,c){if("number"===typeof b)return mb(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
f.nb=function(a,b,c){var d=this;if(d.root.B){if(0<=b&&b<d.i)return Kd(this)<=b?d.X[b&31]=c:(a=function(){return function g(a,k){var l=de(d.root.B,k);if(0===a)l.b[b&31]=c;else{var m=b>>>a&31,p=g(a-5,l.b[m]);l.b[m]=p}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.i)return jb(this,c);throw Error([z("Index "),z(b),z(" out of bounds for TransientVector of length"),z(d.i)].join(""));}throw Error("assoc! after persistent!");};
f.Y=function(){if(this.root.B)return this.i;throw Error("count after persistent!");};f.P=function(a,b){if(this.root.B)return Pd(this,b)[b&31];throw Error("nth after persistent!");};f.ea=function(a,b,c){return 0<=b&&b<this.i?A.a(this,b):c};f.R=function(a,b){return Ja.g(this,b,null)};f.I=function(a,b,c){return"number"===typeof b?A.g(this,b,c):c};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.R(null,c);case 3:return this.I(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.R(null,c)};a.g=function(a,c,d){return this.I(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.c=function(a){return this.R(null,a)};f.a=function(a,b){return this.I(null,a,b)};function fe(){this.h=2097152;this.A=0}
fe.prototype.equiv=function(a){return this.m(null,a)};fe.prototype.m=function(){return!1};var ge=new fe;function he(a,b){return Dc(xc(b)?lc(a)===lc(b)?qd(Ic,U.a(function(a){return O.a(Kb(b,M(a),ge),M(N(a)))},a)):null:null)}function ie(a){this.v=a}ie.prototype.next=function(){if(null!=this.v){var a=M(this.v),b=Q(a,0),a=Q(a,1);this.v=N(this.v);return{value:[b,a],done:!1}}return{value:null,done:!0}};function je(a){return new ie(J(a))}
function ke(a,b){var c;if(b instanceof R)a:{c=a.length;for(var d=b.Ga,e=0;;){if(c<=e){c=-1;break a}if(a[e]instanceof R&&d===a[e].Ga){c=e;break a}e+=2}}else if("string"==typeof b||"number"===typeof b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(b===a[d]){c=d;break a}d+=2}else if(b instanceof Jb)a:for(c=a.length,d=b.Ia,e=0;;){if(c<=e){c=-1;break a}if(a[e]instanceof Jb&&d===a[e].Ia){c=e;break a}e+=2}else if(null==b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(null==a[d]){c=d;break a}d+=2}else a:for(c=
a.length,d=0;;){if(c<=d){c=-1;break a}if(O.a(b,a[d])){c=d;break a}d+=2}return c}function le(a,b,c){this.b=a;this.j=b;this.da=c;this.h=32374990;this.A=0}f=le.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.da};f.Z=function(){return this.j<this.b.length-2?new le(this.b,this.j+2,this.da):null};f.Y=function(){return(this.b.length-this.j)/2};f.H=function(){return Sb(this)};f.m=function(a,b){return fc(this,b)};
f.U=function(a,b){return Ec(b,this)};f.V=function(a,b,c){return Hc(b,c,this)};f.W=function(){return new S(null,2,5,kd,[this.b[this.j],this.b[this.j+1]],null)};f.aa=function(){return this.j<this.b.length-2?new le(this.b,this.j+2,this.da):Nb};f.T=function(){return this};f.N=function(a,b){return new le(this.b,this.j,b)};f.O=function(a,b){return P(b,this)};le.prototype[Aa]=function(){return Pb(this)};function me(a,b,c){this.b=a;this.j=b;this.i=c}me.prototype.ga=function(){return this.j<this.i};
me.prototype.next=function(){var a=new S(null,2,5,kd,[this.b[this.j],this.b[this.j+1]],null);this.j+=2;return a};function r(a,b,c,d){this.o=a;this.i=b;this.b=c;this.l=d;this.h=16647951;this.A=8196}f=r.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.keys=function(){return Pb(ne.c?ne.c(this):ne.call(null,this))};f.entries=function(){return je(J(this))};f.values=function(){return Pb(pe.c?pe.c(this):pe.call(null,this))};
f.has=function(a){return Kb(this,a,Cc)===Cc?!1:!0};f.get=function(a,b){return this.I(null,a,b)};f.forEach=function(a){for(var b=J(this),c=null,d=0,e=0;;)if(e<d){var g=c.P(null,e),h=Q(g,0),g=Q(g,1);a.a?a.a(g,h):a.call(null,g,h);e+=1}else if(b=J(b))zc(b)?(c=ob(b),b=pb(b),h=c,d=lc(c),c=h):(c=M(b),h=Q(c,0),g=Q(c,1),a.a?a.a(g,h):a.call(null,g,h),b=N(b),c=null,d=0),e=0;else return null};f.R=function(a,b){return Ja.g(this,b,null)};f.I=function(a,b,c){a=ke(this.b,b);return-1===a?c:this.b[a+1]};
f.Da=function(){return new me(this.b,0,2*this.i)};f.L=function(){return this.o};f.Y=function(){return this.i};f.H=function(){var a=this.l;return null!=a?a:this.l=a=Ub(this)};f.m=function(a,b){if(null!=b&&(b.h&1024||b.wb)){var c=this.b.length;if(this.i===b.Y(null))for(var d=0;;)if(d<c){var e=b.I(null,this.b[d],Cc);if(e!==Cc)if(O.a(this.b[d+1],e))d+=2;else return!1;else return!1}else return!0;else return!1}else return he(this,b)};f.Ra=function(){return new qe({},this.b.length,Ba(this.b))};
f.U=function(a,b){return Ec(b,this)};f.V=function(a,b,c){return Hc(b,c,this)};f.Qa=function(a,b,c){a=ke(this.b,b);if(-1===a){if(this.i<re){a=this.b;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new r(this.o,this.i+1,e,null)}a=rc;null!=a?null!=a&&(a.A&4||a.Nb)?(d=Fc(jb,ib(a),this),d=kb(d),a=uc(d,vc(a))):a=Fc(Ea,a,this):a=Fc(ic,Nb,this);return Wa(Ka(a,b,c),this.o)}if(c===this.b[a+1])return this;b=Ba(this.b);b[a+1]=c;return new r(this.o,this.i,b,null)};
f.T=function(){var a=this.b;return 0<=a.length-2?new le(a,0,null):null};f.N=function(a,b){return new r(b,this.i,this.b,this.l)};f.O=function(a,b){if(yc(b))return Ka(this,A.a(b,0),A.a(b,1));for(var c=this,d=J(b);;){if(null==d)return c;var e=M(d);if(yc(e))c=Ka(c,A.a(e,0),A.a(e,1)),d=N(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.R(null,c);case 3:return this.I(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.R(null,c)};a.g=function(a,c,d){return this.I(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.c=function(a){return this.R(null,a)};f.a=function(a,b){return this.I(null,a,b)};var pd=new r(null,0,[],Vb),re=8;r.prototype[Aa]=function(){return Pb(this)};
function qe(a,b,c){this.Oa=a;this.Ma=b;this.b=c;this.h=258;this.A=56}f=qe.prototype;f.Y=function(){if(v(this.Oa))return Kc(this.Ma);throw Error("count after persistent!");};f.R=function(a,b){return Ja.g(this,b,null)};f.I=function(a,b,c){if(v(this.Oa))return a=ke(this.b,b),-1===a?c:this.b[a+1];throw Error("lookup after persistent!");};
f.Ya=function(a,b){if(v(this.Oa)){if(null!=b?b.h&2048||b.xb||(b.h?0:w(Na,b)):w(Na,b))return lb(this,se.c?se.c(b):se.call(null,b),te.c?te.c(b):te.call(null,b));for(var c=J(b),d=this;;){var e=M(c);if(v(e))c=N(c),d=lb(d,se.c?se.c(e):se.call(null,e),te.c?te.c(e):te.call(null,e));else return d}}else throw Error("conj! after persistent!");};f.Za=function(){if(v(this.Oa))return this.Oa=!1,new r(null,Kc(this.Ma),this.b,null);throw Error("persistent! called twice");};
f.Sa=function(a,b,c){if(v(this.Oa)){a=ke(this.b,b);if(-1===a){if(this.Ma+2<=2*re)return this.Ma+=2,this.b.push(b),this.b.push(c),this;a=ue.a?ue.a(this.Ma,this.b):ue.call(null,this.Ma,this.b);return lb(a,b,c)}c!==this.b[a+1]&&(this.b[a+1]=c);return this}throw Error("assoc! after persistent!");};function ue(a,b){for(var c=ib(rc),d=0;;)if(d<a)c=lb(c,b[d],b[d+1]),d+=2;else return c}function ve(){this.ma=!1}
function we(a,b){return a===b?!0:a===b||a instanceof R&&b instanceof R&&a.Ga===b.Ga?!0:O.a(a,b)}function xe(a,b,c){a=Ba(a);a[b]=c;return a}function ye(a,b,c,d){a=a.Ka(b);a.b[c]=d;return a}function ze(a,b,c,d){this.b=a;this.j=b;this.Ua=c;this.ja=d}ze.prototype.advance=function(){for(var a=this.b.length;;)if(this.j<a){var b=this.b[this.j],c=this.b[this.j+1];null!=b?b=this.Ua=new S(null,2,5,kd,[b,c],null):null!=c?(b=vb(c),b=b.ga()?this.ja=b:!1):b=!1;this.j+=2;if(b)return!0}else return!1};
ze.prototype.ga=function(){var a=null!=this.Ua;return a?a:(a=null!=this.ja)?a:this.advance()};ze.prototype.next=function(){if(null!=this.Ua){var a=this.Ua;this.Ua=null;return a}if(null!=this.ja)return a=this.ja.next(),this.ja.ga()||(this.ja=null),a;if(this.advance())return this.next();throw Error("No such element");};ze.prototype.remove=function(){return Error("Unsupported operation")};function Ae(a,b,c){this.B=a;this.K=b;this.b=c}f=Ae.prototype;
f.Ka=function(a){if(a===this.B)return this;var b=Lc(this.K),c=Array(0>b?4:2*(b+1));Bc(this.b,0,c,0,2*b);return new Ae(a,this.K,c)};f.Ta=function(){return Be?Be(this.b):Ce.call(null,this.b)};f.La=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.K&e))return d;var g=Lc(this.K&e-1),e=this.b[2*g],g=this.b[2*g+1];return null==e?g.La(a+5,b,c,d):we(c,e)?g:d};
f.ia=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=Lc(this.K&h-1);if(0===(this.K&h)){var l=Lc(this.K);if(2*l<this.b.length){a=this.Ka(a);b=a.b;g.ma=!0;a:for(c=2*(l-k),g=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[g];--l;--c;--g}b[2*k]=d;b[2*k+1]=e;a.K|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=De.ia(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0!==
(this.K>>>d&1)&&(k[d]=null!=this.b[e]?De.ia(a,b+5,Hb(this.b[e]),this.b[e],this.b[e+1],g):this.b[e+1],e+=2),d+=1;else break;return new Ee(a,l+1,k)}b=Array(2*(l+4));Bc(this.b,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;Bc(this.b,2*k,b,2*(k+1),2*(l-k));g.ma=!0;a=this.Ka(a);a.b=b;a.K|=h;return a}l=this.b[2*k];h=this.b[2*k+1];if(null==l)return l=h.ia(a,b+5,c,d,e,g),l===h?this:ye(this,a,2*k+1,l);if(we(d,l))return e===h?this:ye(this,a,2*k+1,e);g.ma=!0;g=b+5;d=Fe?Fe(a,g,l,h,c,d,e):Ge.call(null,a,g,l,h,c,d,e);e=2*k;k=
2*k+1;a=this.Ka(a);a.b[e]=null;a.b[k]=d;return a};
f.ha=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=Lc(this.K&g-1);if(0===(this.K&g)){var k=Lc(this.K);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=De.ha(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.K>>>c&1)&&(h[c]=null!=this.b[d]?De.ha(a+5,Hb(this.b[d]),this.b[d],this.b[d+1],e):this.b[d+1],d+=2),c+=1;else break;return new Ee(null,k+1,h)}a=Array(2*(k+1));Bc(this.b,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;Bc(this.b,2*h,a,2*(h+1),2*(k-h));e.ma=!0;return new Ae(null,this.K|g,a)}var l=this.b[2*h],g=this.b[2*h+1];if(null==l)return k=g.ha(a+5,b,c,d,e),k===g?this:new Ae(null,this.K,xe(this.b,2*h+1,k));if(we(c,l))return d===g?this:new Ae(null,this.K,xe(this.b,2*h+1,d));e.ma=!0;e=this.K;k=this.b;a+=5;a=He?He(a,l,g,b,c,d):Ge.call(null,a,l,g,b,c,d);c=2*h;h=2*h+1;d=Ba(k);d[c]=null;d[h]=a;return new Ae(null,e,d)};f.Da=function(){return new ze(this.b,0,null,null)};
var De=new Ae(null,0,[]);function Ie(a,b,c){this.b=a;this.j=b;this.ja=c}Ie.prototype.ga=function(){for(var a=this.b.length;;){if(null!=this.ja&&this.ja.ga())return!0;if(this.j<a){var b=this.b[this.j];this.j+=1;null!=b&&(this.ja=vb(b))}else return!1}};Ie.prototype.next=function(){if(this.ga())return this.ja.next();throw Error("No such element");};Ie.prototype.remove=function(){return Error("Unsupported operation")};function Ee(a,b,c){this.B=a;this.i=b;this.b=c}f=Ee.prototype;
f.Ka=function(a){return a===this.B?this:new Ee(a,this.i,Ba(this.b))};f.Ta=function(){return Je?Je(this.b):Ke.call(null,this.b)};f.La=function(a,b,c,d){var e=this.b[b>>>a&31];return null!=e?e.La(a+5,b,c,d):d};f.ia=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.b[h];if(null==k)return a=ye(this,a,h,De.ia(a,b+5,c,d,e,g)),a.i+=1,a;b=k.ia(a,b+5,c,d,e,g);return b===k?this:ye(this,a,h,b)};
f.ha=function(a,b,c,d,e){var g=b>>>a&31,h=this.b[g];if(null==h)return new Ee(null,this.i+1,xe(this.b,g,De.ha(a+5,b,c,d,e)));a=h.ha(a+5,b,c,d,e);return a===h?this:new Ee(null,this.i,xe(this.b,g,a))};f.Da=function(){return new Ie(this.b,0,null)};function Le(a,b,c){b*=2;for(var d=0;;)if(d<b){if(we(c,a[d]))return d;d+=2}else return-1}function Me(a,b,c,d){this.B=a;this.Fa=b;this.i=c;this.b=d}f=Me.prototype;
f.Ka=function(a){if(a===this.B)return this;var b=Array(2*(this.i+1));Bc(this.b,0,b,0,2*this.i);return new Me(a,this.Fa,this.i,b)};f.Ta=function(){return Be?Be(this.b):Ce.call(null,this.b)};f.La=function(a,b,c,d){a=Le(this.b,this.i,c);return 0>a?d:we(c,this.b[a])?this.b[a+1]:d};
f.ia=function(a,b,c,d,e,g){if(c===this.Fa){b=Le(this.b,this.i,d);if(-1===b){if(this.b.length>2*this.i)return b=2*this.i,c=2*this.i+1,a=this.Ka(a),a.b[b]=d,a.b[c]=e,g.ma=!0,a.i+=1,a;c=this.b.length;b=Array(c+2);Bc(this.b,0,b,0,c);b[c]=d;b[c+1]=e;g.ma=!0;d=this.i+1;a===this.B?(this.b=b,this.i=d,a=this):a=new Me(this.B,this.Fa,d,b);return a}return this.b[b+1]===e?this:ye(this,a,b+1,e)}return(new Ae(a,1<<(this.Fa>>>b&31),[null,this,null,null])).ia(a,b,c,d,e,g)};
f.ha=function(a,b,c,d,e){return b===this.Fa?(a=Le(this.b,this.i,c),-1===a?(a=2*this.i,b=Array(a+2),Bc(this.b,0,b,0,a),b[a]=c,b[a+1]=d,e.ma=!0,new Me(null,this.Fa,this.i+1,b)):O.a(this.b[a],d)?this:new Me(null,this.Fa,this.i,xe(this.b,a+1,d))):(new Ae(null,1<<(this.Fa>>>a&31),[null,this])).ha(a,b,c,d,e)};f.Da=function(){return new ze(this.b,0,null,null)};
function Ge(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 6:return He(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return Fe(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error([z("Invalid arity: "),z(b.length)].join(""));}}
function He(a,b,c,d,e,g){var h=Hb(b);if(h===d)return new Me(null,h,2,[b,c,e,g]);var k=new ve;return De.ha(a,h,b,c,k).ha(a,d,e,g,k)}function Fe(a,b,c,d,e,g,h){var k=Hb(c);if(k===e)return new Me(null,k,2,[c,d,g,h]);var l=new ve;return De.ia(a,b,k,c,d,l).ia(a,b,e,g,h,l)}function Ne(a,b,c,d,e){this.o=a;this.Ha=b;this.j=c;this.v=d;this.l=e;this.h=32374860;this.A=0}f=Ne.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.o};
f.H=function(){var a=this.l;return null!=a?a:this.l=a=Sb(this)};f.m=function(a,b){return fc(this,b)};f.U=function(a,b){return Ec(b,this)};f.V=function(a,b,c){return Hc(b,c,this)};f.W=function(){return null==this.v?new S(null,2,5,kd,[this.Ha[this.j],this.Ha[this.j+1]],null):M(this.v)};f.aa=function(){if(null==this.v){var a=this.Ha,b=this.j+2;return Oe?Oe(a,b,null):Ce.call(null,a,b,null)}var a=this.Ha,b=this.j,c=N(this.v);return Oe?Oe(a,b,c):Ce.call(null,a,b,c)};f.T=function(){return this};
f.N=function(a,b){return new Ne(b,this.Ha,this.j,this.v,this.l)};f.O=function(a,b){return P(b,this)};Ne.prototype[Aa]=function(){return Pb(this)};function Ce(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return Be(arguments[0]);case 3:return Oe(arguments[0],arguments[1],arguments[2]);default:throw Error([z("Invalid arity: "),z(b.length)].join(""));}}function Be(a){return Oe(a,0,null)}
function Oe(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new Ne(null,a,b,null,null);var d=a[b+1];if(v(d)&&(d=d.Ta(),v(d)))return new Ne(null,a,b+2,d,null);b+=2}else return null;else return new Ne(null,a,b,c,null)}function Pe(a,b,c,d,e){this.o=a;this.Ha=b;this.j=c;this.v=d;this.l=e;this.h=32374860;this.A=0}f=Pe.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.o};
f.H=function(){var a=this.l;return null!=a?a:this.l=a=Sb(this)};f.m=function(a,b){return fc(this,b)};f.U=function(a,b){return Ec(b,this)};f.V=function(a,b,c){return Hc(b,c,this)};f.W=function(){return M(this.v)};f.aa=function(){var a=this.Ha,b=this.j,c=N(this.v);return Qe?Qe(null,a,b,c):Ke.call(null,null,a,b,c)};f.T=function(){return this};f.N=function(a,b){return new Pe(b,this.Ha,this.j,this.v,this.l)};f.O=function(a,b){return P(b,this)};Pe.prototype[Aa]=function(){return Pb(this)};
function Ke(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return Je(arguments[0]);case 4:return Qe(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error([z("Invalid arity: "),z(b.length)].join(""));}}function Je(a){return Qe(null,a,0,null)}function Qe(a,b,c,d){if(null==d)for(d=b.length;;)if(c<d){var e=b[c];if(v(e)&&(e=e.Ta(),v(e)))return new Pe(a,b,c+1,e,null);c+=1}else return null;else return new Pe(a,b,c,d,null)}
function Re(a,b,c){this.$=a;this.rb=b;this.jb=c}Re.prototype.ga=function(){return this.jb&&this.rb.ga()};Re.prototype.next=function(){if(this.jb)return this.rb.next();this.jb=!0;return this.$};Re.prototype.remove=function(){return Error("Unsupported operation")};function Se(a,b,c,d,e,g){this.o=a;this.i=b;this.root=c;this.ba=d;this.$=e;this.l=g;this.h=16123663;this.A=8196}f=Se.prototype;f.toString=function(){return xb(this)};f.equiv=function(a){return this.m(null,a)};
f.keys=function(){return Pb(ne.c?ne.c(this):ne.call(null,this))};f.entries=function(){return je(J(this))};f.values=function(){return Pb(pe.c?pe.c(this):pe.call(null,this))};f.has=function(a){return Kb(this,a,Cc)===Cc?!1:!0};f.get=function(a,b){return this.I(null,a,b)};
f.forEach=function(a){for(var b=J(this),c=null,d=0,e=0;;)if(e<d){var g=c.P(null,e),h=Q(g,0),g=Q(g,1);a.a?a.a(g,h):a.call(null,g,h);e+=1}else if(b=J(b))zc(b)?(c=ob(b),b=pb(b),h=c,d=lc(c),c=h):(c=M(b),h=Q(c,0),g=Q(c,1),a.a?a.a(g,h):a.call(null,g,h),b=N(b),c=null,d=0),e=0;else return null};f.R=function(a,b){return Ja.g(this,b,null)};f.I=function(a,b,c){return null==b?this.ba?this.$:c:null==this.root?c:this.root.La(0,Hb(b),b,c)};
f.Da=function(){var a=this.root?vb(this.root):jd;return this.ba?new Re(this.$,a,!1):a};f.L=function(){return this.o};f.Y=function(){return this.i};f.H=function(){var a=this.l;return null!=a?a:this.l=a=Ub(this)};f.m=function(a,b){return he(this,b)};f.Ra=function(){return new Te({},this.root,this.i,this.ba,this.$)};
f.Qa=function(a,b,c){if(null==b)return this.ba&&c===this.$?this:new Se(this.o,this.ba?this.i:this.i+1,this.root,!0,c,null);a=new ve;b=(null==this.root?De:this.root).ha(0,Hb(b),b,c,a);return b===this.root?this:new Se(this.o,a.ma?this.i+1:this.i,b,this.ba,this.$,null)};f.T=function(){if(0<this.i){var a=null!=this.root?this.root.Ta():null;return this.ba?P(new S(null,2,5,kd,[null,this.$],null),a):a}return null};f.N=function(a,b){return new Se(b,this.i,this.root,this.ba,this.$,this.l)};
f.O=function(a,b){if(yc(b))return Ka(this,A.a(b,0),A.a(b,1));for(var c=this,d=J(b);;){if(null==d)return c;var e=M(d);if(yc(e))c=Ka(c,A.a(e,0),A.a(e,1)),d=N(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.R(null,c);case 3:return this.I(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.R(null,c)};a.g=function(a,c,d){return this.I(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ba(b)))};f.c=function(a){return this.R(null,a)};f.a=function(a,b){return this.I(null,a,b)};var rc=new Se(null,0,null,!1,null,Vb);Se.prototype[Aa]=function(){return Pb(this)};
function Te(a,b,c,d,e){this.B=a;this.root=b;this.count=c;this.ba=d;this.$=e;this.h=258;this.A=56}function Ue(a,b,c){if(a.B){if(null==b)a.$!==c&&(a.$=c),a.ba||(a.count+=1,a.ba=!0);else{var d=new ve;b=(null==a.root?De:a.root).ia(a.B,0,Hb(b),b,c,d);b!==a.root&&(a.root=b);d.ma&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=Te.prototype;f.Y=function(){if(this.B)return this.count;throw Error("count after persistent!");};
f.R=function(a,b){return null==b?this.ba?this.$:null:null==this.root?null:this.root.La(0,Hb(b),b)};f.I=function(a,b,c){return null==b?this.ba?this.$:c:null==this.root?c:this.root.La(0,Hb(b),b,c)};
f.Ya=function(a,b){var c;a:if(this.B)if(null!=b?b.h&2048||b.xb||(b.h?0:w(Na,b)):w(Na,b))c=Ue(this,se.c?se.c(b):se.call(null,b),te.c?te.c(b):te.call(null,b));else{c=J(b);for(var d=this;;){var e=M(c);if(v(e))c=N(c),d=Ue(d,se.c?se.c(e):se.call(null,e),te.c?te.c(e):te.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");return c};f.Za=function(){var a;if(this.B)this.B=null,a=new Se(null,this.count,this.root,this.ba,this.$,null);else throw Error("persistent! called twice");return a};
f.Sa=function(a,b,c){return Ue(this,b,c)};var vd=function vd(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return vd.u(0<c.length?new K(c.slice(0),0):null)};vd.u=function(a){for(var b=J(a),c=ib(rc);;)if(b){a=N(N(b));var d=M(b),b=M(N(b)),c=lb(c,d,b),b=a}else return kb(c)};vd.J=0;vd.G=function(a){return vd.u(J(a))};function Ve(a,b){this.s=a;this.da=b;this.h=32374988;this.A=0}f=Ve.prototype;f.toString=function(){return xb(this)};
f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.da};f.Z=function(){var a=(null!=this.s?this.s.h&128||this.s.Xa||(this.s.h?0:w(Ha,this.s)):w(Ha,this.s))?this.s.Z(null):N(this.s);return null==a?null:new Ve(a,this.da)};f.H=function(){return Sb(this)};f.m=function(a,b){return fc(this,b)};f.U=function(a,b){return Ec(b,this)};f.V=function(a,b,c){return Hc(b,c,this)};f.W=function(){return this.s.W(null).gb()};
f.aa=function(){var a=(null!=this.s?this.s.h&128||this.s.Xa||(this.s.h?0:w(Ha,this.s)):w(Ha,this.s))?this.s.Z(null):N(this.s);return null!=a?new Ve(a,this.da):Nb};f.T=function(){return this};f.N=function(a,b){return new Ve(this.s,b)};f.O=function(a,b){return P(b,this)};Ve.prototype[Aa]=function(){return Pb(this)};function ne(a){return(a=J(a))?new Ve(a,null):null}function se(a){return Oa(a)}function We(a,b){this.s=a;this.da=b;this.h=32374988;this.A=0}f=We.prototype;f.toString=function(){return xb(this)};
f.equiv=function(a){return this.m(null,a)};f.L=function(){return this.da};f.Z=function(){var a=(null!=this.s?this.s.h&128||this.s.Xa||(this.s.h?0:w(Ha,this.s)):w(Ha,this.s))?this.s.Z(null):N(this.s);return null==a?null:new We(a,this.da)};f.H=function(){return Sb(this)};f.m=function(a,b){return fc(this,b)};f.U=function(a,b){return Ec(b,this)};f.V=function(a,b,c){return Hc(b,c,this)};f.W=function(){return this.s.W(null).hb()};
f.aa=function(){var a=(null!=this.s?this.s.h&128||this.s.Xa||(this.s.h?0:w(Ha,this.s)):w(Ha,this.s))?this.s.Z(null):N(this.s);return null!=a?new We(a,this.da):Nb};f.T=function(){return this};f.N=function(a,b){return new We(this.s,b)};f.O=function(a,b){return P(b,this)};We.prototype[Aa]=function(){return Pb(this)};function pe(a){return(a=J(a))?new We(a,null):null}function te(a){return Pa(a)}
function Tc(a){if(null!=a&&(a.A&4096||a.zb))return a.name;if("string"===typeof a)return a;throw Error([z("Doesn't support name: "),z(a)].join(""));}
function Xe(a,b,c,d,e,g,h){var k=ka;ka=null==ka?null:ka-1;try{if(null!=ka&&0>ka)return H(a,"#");H(a,c);if(0===ua.c(g))J(h)&&H(a,function(){var a=Ye.c(g);return v(a)?a:"..."}());else{if(J(h)){var l=M(h);b.g?b.g(l,a,g):b.call(null,l,a,g)}for(var m=N(h),p=ua.c(g)-1;;)if(!m||null!=p&&0===p){J(m)&&0===p&&(H(a,d),H(a,function(){var a=Ye.c(g);return v(a)?a:"..."}()));break}else{H(a,d);var q=M(m);c=a;h=g;b.g?b.g(q,c,h):b.call(null,q,c,h);var t=N(m);c=p-1;m=t;p=c}}return H(a,e)}finally{ka=k}}
function Ze(a,b){for(var c=J(b),d=null,e=0,g=0;;)if(g<e){var h=d.P(null,g);H(a,h);g+=1}else if(c=J(c))d=c,zc(d)?(c=ob(d),e=pb(d),d=c,h=lc(c),c=e,e=h):(h=M(d),H(a,h),c=N(d),d=null,e=0),g=0;else return null}var $e={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function af(a){return[z('"'),z(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return $e[a]})),z('"')].join("")}
function cf(a,b){var c=Dc(I(a,sa));return c?(c=null!=b?b.h&131072||b.yb?!0:!1:!1)?null!=vc(b):c:c}
function df(a,b,c){if(null==a)return H(b,"nil");if(cf(c,a)){H(b,"^");var d=vc(a);V.g?V.g(d,b,c):V.call(null,d,b,c);H(b," ")}if(a.qb)return a.Hb(b);if(null!=a&&(a.h&2147483648||a.S))return a.F(null,b,c);if(!0===a||!1===a||"number"===typeof a)return H(b,""+z(a));if(null!=a&&a.constructor===Object)return H(b,"#js "),d=U.a(function(b){return new S(null,2,5,kd,[Sc.c(b),a[b]],null)},Ac(a)),ef.w?ef.w(d,V,b,c):ef.call(null,d,V,b,c);if(wa(a))return Xe(b,V,"#js ["," ","]",c,a);if("string"==typeof a)return v(qa.c(c))?
H(b,af(a)):H(b,a);if("function"==n(a)){var e=a.name;c=v(function(){var a=null==e;return a?a:/^[\s\xa0]*$/.test(e)}())?"Function":e;return Ze(b,hc(["#object[",c,' "',""+z(a),'"]'],0))}if(a instanceof Date)return c=function(a,b){for(var c=""+z(a);;)if(lc(c)<b)c=[z("0"),z(c)].join("");else return c},Ze(b,hc(['#inst "',""+z(a.getUTCFullYear()),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),
3),"-",'00:00"'],0));if(a instanceof RegExp)return Ze(b,hc(['#"',a.source,'"'],0));if(null!=a&&(a.h&2147483648||a.S))return fb(a,b,c);if(v(a.constructor.$a))return Ze(b,hc(["#object[",a.constructor.$a.replace(RegExp("/","g"),"."),"]"],0));e=a.constructor.name;c=v(function(){var a=null==e;return a?a:/^[\s\xa0]*$/.test(e)}())?"Object":e;return Ze(b,hc(["#object[",c," ",""+z(a),"]"],0))}function V(a,b,c){var d=ff.c(c);return v(d)?(c=qc.g(c,gf,df),d.g?d.g(a,b,c):d.call(null,a,b,c)):df(a,b,c)}
function Ad(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;var e=0<b.length?new K(b.slice(0),0):null,b=ma();(c=null==e)||(c=J(e),c=null==c?!0:!1===c?!0:!1);if(c)b="";else{c=z;d=new ea;a:{var g=new wb(d);V(M(e),g,b);for(var e=J(N(e)),h=null,k=0,l=0;;)if(l<k){var m=h.P(null,l);H(g," ");V(m,g,b);l+=1}else if(e=J(e))h=e,zc(h)?(e=ob(h),k=pb(h),h=e,m=lc(e),e=k,k=m):(m=M(h),H(g," "),V(m,g,b),e=N(h),h=null,k=0),l=0;else break a}b=""+c(d)}return b}
function ef(a,b,c,d){return Xe(c,function(a,c,d){var k=Oa(a);b.g?b.g(k,c,d):b.call(null,k,c,d);H(c," ");a=Pa(a);return b.g?b.g(a,c,d):b.call(null,a,c,d)},"{",", ","}",d,J(a))}K.prototype.S=!0;K.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};Uc.prototype.S=!0;Uc.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};Ne.prototype.S=!0;Ne.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};le.prototype.S=!0;
le.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};Yd.prototype.S=!0;Yd.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};Qc.prototype.S=!0;Qc.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};Se.prototype.S=!0;Se.prototype.F=function(a,b,c){return ef(this,V,b,c)};Pe.prototype.S=!0;Pe.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};be.prototype.S=!0;be.prototype.F=function(a,b,c){return Xe(b,V,"["," ","]",c,this)};Yc.prototype.S=!0;
Yc.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};sd.prototype.S=!0;sd.prototype.F=function(a,b,c){H(b,"#object [cljs.core.Atom ");V(new r(null,1,[hf,this.state],null),b,c);return H(b,"]")};We.prototype.S=!0;We.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};S.prototype.S=!0;S.prototype.F=function(a,b,c){return Xe(b,V,"["," ","]",c,this)};Oc.prototype.S=!0;Oc.prototype.F=function(a,b){return H(b,"()")};r.prototype.S=!0;
r.prototype.F=function(a,b,c){return ef(this,V,b,c)};Ve.prototype.S=!0;Ve.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};Nc.prototype.S=!0;Nc.prototype.F=function(a,b,c){return Xe(b,V,"("," ",")",c,this)};function pc(a){return Math.floor(Math.random()*a)};var jf=new R(null,"L","L",-1038307519),W=new R(null,"new-state","new-state",-490349212),kf=new R(null,"done","done",-889844188),sa=new R(null,"meta","meta",1499536964),ta=new R(null,"dup","dup",556298533),X=new R(null,"R","R",-936662523),od=new Jb(null,"meta9867","meta9867",-1390976569,null),zd=new Jb(null,"new-value","new-value",-1567397401,null),wd=new R(null,"validator","validator",-1966190681),lf=new R(null,"name","name",1843675177),Y=new R(null,"new-color","new-color",703356010),mf=new R(null,
"orientation","orientation",623557579),hf=new R(null,"val","val",128701612),yd=new Jb(null,"validate","validate",1439230700,null),nf=new R(null,"state","state",-1988618099),gf=new R(null,"fallback-impl","fallback-impl",-1501286995),na=new R(null,"flush-on-newline","flush-on-newline",-151457939),Ed=new Jb(null,"n","n",-2092305744,null),qa=new R(null,"readably","readably",1129599760),Ye=new R(null,"more-marker","more-marker",-14717935),ua=new R(null,"print-length","print-length",1931866356),Z=new R(null,
"rotate","rotate",152705015),nd=new Jb(null,"quote","quote",1377916282,null),md=new R(null,"arglists","arglists",1661989754),ld=new Jb(null,"nil-iter","nil-iter",1101030523,null),ff=new R(null,"alt-impl","alt-impl",670969595),of=new R(null,"U","U",1362002044),pf=new R(null,"N","N",-640629860),Dd=new Jb(null,"number?","number?",-1747282210,null);function qf(a){return v(!1)?console.log(fd(z,a)):null}
var rf=ud?ud(0):td.call(null,0),sf=ud?ud(jc):td.call(null,jc),oc=new S(null,17,5,kd,[new r(null,3,[0,new r(null,2,[0,new r(null,3,[Z,jf,Y,1,W,1],null),1,new r(null,3,[Z,jf,Y,1,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Z,X,Y,1,W,1],null),1,new r(null,3,[Z,pf,Y,0,W,0],null)],null),lf,"Fibonacci"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Z,X,Y,1,W,0],null),1,new r(null,3,[Z,jf,Y,0,W,0],null)],null),1,new r(null,2,[0,new r(null,3,[Z,X,Y,1,W,0],null),1,new r(null,3,[Z,jf,Y,0,W,0],null)],
null),lf,"Langton"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Z,X,Y,1,W,0],null),1,new r(null,3,[Z,X,Y,1,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Z,pf,Y,0,W,0],null),1,new r(null,3,[Z,pf,Y,0,W,1],null)],null),lf,"Chaotic 1"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Z,X,Y,1,W,1],null),1,new r(null,3,[Z,jf,Y,0,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Z,pf,Y,1,W,0],null),1,new r(null,3,[Z,pf,Y,0,W,0],null)],null),lf,"Chaotic 2"],null),new r(null,3,[0,new r(null,
2,[0,new r(null,3,[Z,jf,Y,1,W,1],null),1,new r(null,3,[Z,jf,Y,0,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Z,X,Y,1,W,1],null),1,new r(null,3,[Z,jf,Y,0,W,0],null)],null),lf,"Chaotic 3"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Z,X,Y,1,W,1],null),1,new r(null,3,[Z,X,Y,0,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Z,pf,Y,1,W,0],null),1,new r(null,3,[Z,pf,Y,1,W,1],null)],null),lf,"Chaotic 4"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,1,Z,X,W,1],null),1,new r(null,3,
[Y,1,Z,jf,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Y,1,Z,X,W,1],null),1,new r(null,3,[Y,0,Z,jf,W,0],null)],null),lf,"Coral"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,1,Z,jf,W,0],null),1,new r(null,3,[Y,1,Z,X,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Y,0,Z,X,W,0],null),1,new r(null,3,[Y,0,Z,jf,W,1],null)],null),lf,"Square 1"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,0,Z,X,W,1],null),1,new r(null,3,[Y,0,Z,jf,W,0],null)],null),1,new r(null,2,[0,new r(null,3,
[Y,1,Z,pf,W,0],null),1,new r(null,3,[Y,1,Z,of,W,1],null)],null),lf,"Square 2"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,0,Z,pf,W,1],null),1,new r(null,3,[Y,0,Z,of,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Y,1,Z,X,W,1],null),1,new r(null,3,[Y,0,Z,pf,W,1],null)],null),lf,"Counter 1"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,1,Z,X,W,1],null),1,new r(null,3,[Y,0,Z,pf,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Y,0,Z,pf,W,0],null),1,new r(null,3,[Y,1,Z,jf,W,1],null)],
null),lf,"Counter 2"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,1,Z,pf,W,1],null),1,new r(null,3,[Y,1,Z,jf,W,0],null)],null),1,new r(null,2,[0,new r(null,3,[Y,1,Z,X,W,1],null),1,new r(null,3,[Y,0,Z,pf,W,0],null)],null),lf,"Spiral 1"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,1,Z,jf,W,0],null),1,new r(null,3,[Y,0,Z,X,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Y,1,Z,X,W,0],null),1,new r(null,3,[Y,0,Z,jf,W,1],null)],null),lf,"Spiral 2"],null),new r(null,3,[0,new r(null,
2,[0,new r(null,3,[Y,1,Z,of,W,0],null),1,new r(null,3,[Y,0,Z,pf,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Y,0,Z,jf,W,0],null),1,new r(null,3,[Y,0,Z,X,W,1],null)],null),lf,"Spiral 3"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,0,Z,pf,W,1],null),1,new r(null,3,[Y,1,Z,of,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Y,1,Z,jf,W,0],null),1,new r(null,3,[Y,1,Z,pf,W,1],null)],null),lf,"Ladder"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,0,Z,X,W,1],null),1,new r(null,3,[Y,
0,Z,jf,W,0],null)],null),1,new r(null,2,[0,new r(null,3,[Y,1,Z,of,W,1],null),1,new r(null,3,[Y,0,Z,X,W,0],null)],null),lf,"Dixe"],null),new r(null,3,[0,new r(null,2,[0,new r(null,3,[Y,1,Z,jf,W,0],null),1,new r(null,3,[Y,0,Z,X,W,1],null)],null),1,new r(null,2,[0,new r(null,3,[Y,0,Z,X,W,0],null),1,new r(null,3,[Y,1,Z,X,W,0],null)],null),lf,"Diamond"],null)],null);function tf(a,b,c){return Hd.g(a,b,function(){return c})}
function uf(a,b,c){Bd.a(sf,function(d){return tf(d,new S(null,2,5,kd,[a,b],null),c)})}function vf(a,b){return Gd(Xb.c?Xb.c(sf):Xb.call(null,sf),new S(null,2,5,kd,[a,b],null))}function wf(a,b){var c=Q(a,0),d=Q(a,1);b.fillStyle="rgb(200, 0, 0)";b.fillRect(4*c,4*d,4,4)}function xf(a,b){var c=Q(a,0),d=Q(a,1),e=vf(c,d),e=O.a(1,e)?"rgb(0, 0, 0)":"rgb(255, 255, 255)";b.strokeStyle=e;b.fillStyle=e;b.fillRect(4*c,4*d,4,4)}
function yf(a,b){var c=function(){if(v(O.a?O.a(jf,a):O.call(null,jf,a)))return-90;if(v(O.a?O.a(X,a):O.call(null,X,a)))return 90;if(v(O.a?O.a(pf,a):O.call(null,pf,a)))return 0;if(v(O.a?O.a(of,a):O.call(null,of,a)))return 180;throw Error([z("No matching clause: "),z(a)].join(""));}()+b;return 360<=c?c-360:0>c?c+360:c}
function zf(a,b,c){var d=Q(a,0);a=Q(a,1);b=null!=b&&(b.h&64||b.Ea)?fd(vd,b):b;var e=I(b,nf);b=I(b,mf);var g=vf(d,a);c=Gd(c,new S(null,2,5,kd,[e,v(g)?g:0],null));g=null!=c&&(c.h&64||c.Ea)?fd(vd,c):c;c=I(g,Y);e=I(g,W);g=I(g,Z);uf(d,a,c);return new r(null,2,[nf,e,mf,yf(g,b)],null)}
function Af(a,b){var c=null!=a&&(a.h&64||a.Ea)?fd(vd,a):a,d=I(c,mf),c=function(){if(v(O.a?O.a(0,d):O.call(null,0,d)))return new S(null,2,5,kd,[0,-1],null);if(v(O.a?O.a(90,d):O.call(null,90,d)))return new S(null,2,5,kd,[1,0],null);if(v(O.a?O.a(180,d):O.call(null,180,d)))return new S(null,2,5,kd,[0,1],null);if(v(O.a?O.a(270,d):O.call(null,270,d)))return new S(null,2,5,kd,[-1,0],null);throw Error([z("No matching clause: "),z(d)].join(""));}();return U.g(Jc,b,c)}
var Bf=function Bf(b,c,d,e,g){try{xf(b,e);Bd.a(rf,Wb);var h=zf(b,c,g),k=Af(h,b);return v(d.c?d.c(k):d.call(null,k))?(wf(k,e),setTimeout(function(b,c){return function(){return Bf(c,b,d,e,g)}}(h,k),40)):qf(hc([[z(kf),z(" old: "),z(b),z(" new: "),z(k)].join("")],0))}catch(l){if(l instanceof RangeError)return qf(hc(["Catched ",l],0));throw l;}};function Cf(a,b){return function(c){var d=Q(c,0);c=Q(c,1);return d<=a&&c<=b&&0<=d&&0<=c}}
function Df(a){var b=document.getElementById(a),c=b.width/4|0;a=b.height/4|0;var b=b.getContext("2d"),d=Cf(c,a),e=nc();qf(hc(["Running pattern ",lf.c(e)],0));var g;g=Xd(Cd(c+1,Fd(0)));g=Cd(a+1,Fd(g));g=Xd(g);xd.a?xd.a(sf,g):xd.call(null,sf,g);g=pc(2);c=c/2|0;a=a/2|0;uf(c,a,pc(2));Bf(new S(null,2,5,kd,[c,a],null),new r(null,2,[nf,g,mf,0],null),d,b,e);return lf.c(e)}var Ef=["langtons_ant","core","run"],Ff=this;Ef[0]in Ff||!Ff.execScript||Ff.execScript("var "+Ef[0]);
for(var Gf;Ef.length&&(Gf=Ef.shift());){var Hf;if(Hf=!Ef.length)Hf=void 0!==Df;Hf?Ff[Gf]=Df:Ff=Ff[Gf]?Ff[Gf]:Ff[Gf]={}};
})();

//# sourceMappingURL=langtons_ant.map